### ISSUE TITLE
how to add functionality of skip the ads

### ISSUE THREAD

**Issue by mubbashar** [videojs/videojs-contrib-ads#102]
I want to have the functionality of skiping the ad. how can i do this?

**Comment by gangstaJS** [comment]
Use ``` player.ads.endLinearAdMode(); ```

**Comment by bclwhitaker** [comment]
Hi @mubbashar. The functionality for skipping ads is typically a feature provided by an advertising SDK.  You should consult the SDK documentation for the ad provider that you are using to learn how to enable it.  Typically, its as simple as enabling it on the ad inventory side to make sure that the VAST tag response contains the right xml to make the button appear.

For example, here is some documentation for doubleclick:
https://support.google.com/dfp_premium/answer/3376934?hl=en

This project only attempts to make handling the different states (both functional and visual) that a player with advertising in it might need.  It doesn't handle any playback or interaction with the actual advertisements and/or the sdk.

**Comment by mubbashar** [comment]
Ok i tried to implement the skip functionality. but player.ads.endLinearAdMode(); did not work. it did not close the ads. 
here is the demo url : https://vimleo.com/newapp/?action=show_player&the_id=1

**Comment by gangstaJS** [comment]
@mubbashar, I for some reason does not play in your advertising demo

**Comment by mubbashar** [comment]
@gangstaJS Just made a video for you. http://youtu.be/K2EBcNfWMiQ

**Comment by gangstaJS** [comment]
@mubbashar see my  realization github.com/gangstaJS/foxplayer
