### ISSUE TITLE
Add a video with two prerolls to the examples

### ISSUE THREAD

**Issue by gangstaJS** [videojs/videojs-contrib-ads#103]
Please write an example of two video prerole.

**Comment by gkatsev** [comment]
In the [`example/`](https://github.com/videojs/videojs-contrib-ads/tree/master/example) folder, we have an example that has a preroll, midroll, and postroll.

**Comment by gangstaJS** [comment]
And where there is the example of two video prerole?

**Comment by chemoish** [comment]
It's definitely possible, but perhaps the `example/` or code isn't as clear as it could be.

The first step is to identify the `events` you can listen to. See https://github.com/videojs/videojs-contrib-ads/blob/master/migrating-to-2.0.md.

Many events are now prefixed with `ad`. However, `ended` is now `contentended` apparently.

Once you identify the events you can play with, you need to understand `startLinearAdMode()` and `endLinearAdMode()`.

---

Here is a *possible* example of how you can do a two video preroll.

```js
videojs('player_id', {}, function () {
    var player = this;
    
    player.ads();
    
    player.on('contentupdate', function () {
        // go fetch ads somehow—there might be more to this to 
        // prevent the video from playing before the ad
        fetchAdsSomehow().then(function () {
            player.trigger('adsready');
        });
    });
    
    player.on('readyforpreroll', function () {
        player.ads.startLinearAdMode();
        
        player.src('preroll-1.mp4');
        
        // please don't write this kind of code though…
        player.one('adended', function () {
            player.src('preroll-2.mp4');
            
            player.one('adended', function () {
                player.ads.endLinearAdMode();
            });
        });
    });
});
```

**Comment by chemoish** [comment]
Also, perhaps, read https://github.com/videojs/videojs-contrib-ads/issues/108

**Comment by gangstaJS** [comment]
This embodiment does not work on firefox
```javascript
player.one('adended', function () {
            player.src('preroll-2.mp4');

            player.one('adended', function () {
                player.ads.endLinearAdMode();
            });
        });
```

I decided it so:

```javascript
player.one('adended', function () {
           setTimeout(player.src.bind(player, 'preroll-2.mp4'), 0);

            player.one('adended', function () {
                player.ads.endLinearAdMode();
            });
        });
```

**Comment by gangstaJS** [comment]
But I do after each preroll `player.ads.endLinearAdMode();`. That's wrong?

**Comment by gangstaJS** [comment]
Please look at my decision https://github.com/gangstaJS/foxplayer/blob/ads_foxplayer/js/vjs-prepare-data.js

**Comment by incompl** [comment]
It's been a couple years and we haven't prioritized this, so I'm closing.
