### ISSUE TITLE
Preroll for encrypted media.

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-ads#104]
Many of the plugins for videojs seem out-of-date and I suspect the same for `videojs-preroll`.

Thusly, I figured I would just tap into the default preroll provided by `videojs-contrib-ads`.

``` js
window.player = videojs('player', {
    controls: true
}, function () {
    this.ads();

    this.on('contentupdate', function () {
        player.trigger('adsready');
    });

    this.on('readyforpreroll', function () {
        this.ads.startLinearAdMode();

        this.src('http://example.com/example.mp4');

        // not sure if this is needed
        this.one('durationchange', function () {
            this.play();
        });

        this.one('adended', function () {
            player.ads.endLinearAdMode();
        });
    });
});
```

Anyways, the default implementation looks fine and dandy for prerolling a clip, but for embedded content not everything gets carried over…

https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.js#L153

``` js
snapshot = {
    ended: player.ended(),
    src: player.currentSrc(),
    currentTime: player.currentTime(),
    type: player.currentType()
};
```

The snapshot of the current player doesn't carry over `keySystemOptions` to be passed to…

https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.js#L316

``` js
// if the src changed for ad playback, reset it
player.src({ src: snapshot.src, type: snapshot.type });
```

See: https://github.com/videojs/videojs-contrib-dash

``` js
player.src({
    src: 'http://example.com/my/manifest.mpd',
    type: 'application/dash+xml',
    keySystemOptions: [{
        name: 'com.widevine.alpha',
        options: {
            licenseUrl: 'http://m.widevine.com/proxy'
        }
    }]
});
```

Currently the only way I see getting keySystemOptions would be to access `player.tech.currentSource_.keySystemOptions` which is https://38.media.tumblr.com/avatar_3264e03aabff_128.png.

Since this is crossing between tech and plugin… Any recommendations?

**Comment by incompl** [comment]
My recommendation would be to try making a PR to contrib-ads for checking for this value when creating / restoring the snapshot. Besides that you'd probably need to handle it outside of contrib-ads.

**Comment by gkatsev** [comment]
This reminds me, in videojs, we finally merged in the `currentSource()` PR, I wonder if using it in contrib-ads would help it. Basically, just snapshot the whole source object given whatever videojs gives us and then make sure that videojs keeps the keySystemOptions option around.

**Comment by incompl** [comment]
That's a great idea

**Comment by incompl** [comment]
This was added in 3.1.1 I believe.
