### ISSUE TITLE
How do you distinguish between postroll ended and main content ended?

### ISSUE THREAD

**Issue by brkattk** [videojs/videojs-contrib-ads#106]
I'm having a tough time being able to distinguish between my video ending and any of the ads ending. They all seem to fire an 'ended' event.

**Comment by chemoish** [comment]
The example in the README is actually incorrect.

You're actually looking for an event called `adended`.

```js
// when it's finished
player.one('adended', function() {
    // play your linear ad content, then when it's finished ...
    player.ads.endLinearAdMode();
});
```

https://github.com/videojs/videojs-contrib-ads/blob/master/example/example-integration.js#L78

**Comment by chemoish** [comment]
Also note that the README should be…

```js
player.one('durationchange', function(){
    player.play();
});
```
