### ISSUE TITLE
Proposal for Generic Ad Info and Events

### ISSUE THREAD

**Issue by bclwhitaker** [videojs/videojs-contrib-ads#114]
### Background:

Each ad provider emits a unique set of events.  Typically, these events are used to track the state of ad playback for metrics purposes and to create custom UI's.  However, the names of these events and the data exposed in them can be wildly different from one provider to the next not to mention the differences from the same provider across techs (flash vs. html).  This means that custom UI's need to be built differently for each ad provider you work with and often each tech for that provider as well.
### Proposal:

By defining a common set of events and objects that ad poviders can integrate with in contrib-ads, custom UIs and analytics providers can be provider agnostic.
#### Events:

**ads-request** _Fired when ad data is requested._
**ads-load:**  _Fired when ad data is available following an ad request._
**ads-pod-started:**  _Fired when a LINEAR ad pod has started._
**ads-pod-ended:**  _Fired when a LINEAR ad pod has completed._
**ads-allpods-completed:**  _Fired when all LINEAR ads are completed._
**ads-ad-started:**  _Fired when the ad starts playing._
**ads-ad-ended:**  _Fired when the ad completes playing._
**ads-first-quartile:**  _Fired when the ad playhead crosses first quartile._
**ads-midpoint:**  _Fired when the ad playhead crosses midpoint._
**ads-third-quartile:**  _Fired when the ad playhead crosses third quartile._
**ads-pause:**  _Fired when the ad is paused._
**ads-play:**  _Fired when the ad is resumed._
**ads-mute:**  _Fired when the ad volume has been muted._
**ads-click:**  _Fired when the ad is clicked._
#### Provider Info:

``` json
player.ads.provider = {
  "type": `String`,
  "event": `Object`
}
```
#### Ad Info:

``` json
player.ads.ad = {
  "type": `String`,
  "index": `Number`,
  "id": `String`,
  "duration": `Number`,
  "currentTime": `Function`
}
```
#### Ad Grouping (pod) Info:

``` json
player.ads.pod = {
  "id": `String`,
  "duration": `Number`,
  "size": `Number`,
  "currentTime": `Function`
}
```
#### Guidelines
- Everything but `player.ads.provider.type` is _undefined_ during content-playback.
- The type of ad should be one of 'PREROLL', 'MIDROLL', 'POSTROLL'
- All objects and properties should be considered read-only to everyone but the ad providers.

**Comment by dmlap** [comment]
Some suggestions on event naming to be more consistent with HTML events:

__ads-data-loaded__ -> __ads-load__
__ads-paused__ -> __ad-pause__
__ads-resumed__ -> __ads-play__
__ads-muted__: create a more generic __ads-volumechange__ event instead
__ads-clicked__ -> __ads-click__

**Comment by bclwhitaker** [comment]
I'm on board for the new names.  Will update.  

But for the volumechange, I don't know if that level of detail is necessary or available from all ad providers.  Most of the events I'm proposing map directly to IAB requirements for ad tracking.  `mute` is on that list, but detailed volume changes aren't and requiring the extra step (though trivial) for the mute check which they will have to implement seems worthwhile.

**Comment by dmlap** [comment]
That makes sense. I think we could provide some guidance around the `volumechange` event that indicated it was not a strict requirement and implementations could choose to only fire it when changing between muted and unmuted states, for instance.

**Comment by mister-ben** [comment]
**ads-error** and **ads-request** would be useful for custom analytics.

**Comment by bclwhitaker** [comment]
ads-request sounds reasonable to fire when the request for ad info/vast response is made.  Will add that.  

I'm hesitant to define a generic ads-error event as that can mean a whole lot of different things and starts us down a slippery slope of trying to define what an error is across all ad integrations.  Also, there is already an 'adserror' event in contrib-ads as part of the ad state handling mechanism.  I don't want to redefine/confuse things by adding a different type of error event.  I'm hoping the new `skipLinearAdMode` method that was added recently will start to replace the overloaded use of `adserror` as a mechanism to abandon or skip ads so that its more reliable just as an indicator for  an error.

**Comment by bclwhitaker** [comment]
I've removed the linear property from the ad object from this proposal.  Since both a linear and non-linear ad could be playing at the same time, using the a single object to represent them both could become unreliable.  These guidelines should be considered only for linear ads and a definition of what events, objects, and properties look like for non-linears can be dealt with later.

**Comment by incompl** [comment]
This proposal has been accepted and added to the readme.
