### ISSUE TITLE
Can I add multiple VAST tags in  a single Player, means, if one vast ad  has failed to load,then take the other  one

### ISSUE THREAD

**Issue by Shakvs** [videojs/videojs-contrib-ads#117]
I have integrated  IMA SDK Plugin for Video.js html player for my website.(followed this link https://github.com/googleads/videojs-ima). Now the  test  Vast ad is coming .
But I need to know Can I add multiple VAST tags in  a single Player means if one vast ad  is failed to load ,then take the other  one. 
I searched on internet , I couldn't seen  any  answer   for this . 
Is there any Waterfalls or fallback plugins  available for Videojs for Vast?
It would be great if  you could give me any answer.
Awaiting for your reply.

**Comment by vkdimitrov** [comment]
same thought

**Comment by hyurtseven81** [comment]
You can use VMAP standart, it is a simple xml format that you can generate easyly and you can set one or more preroll, midroll, postroll vast targets and bumbers like presents, presented etc.

for example:

https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostpodbumper&cmsid=496&vid=short_onecue&correlator=

**Comment by vkdimitrov** [comment]
Nice,I just need one clarification. In your example just one of "preroll-post-bumper" and "preroll-ad-1" will be played right? So if "preroll-post-bumper" returns no ad the player will fallback to "preroll-ad-1"?

**Comment by hyurtseven81** [comment]
Player tries to play first preroll if there is no ad in that than player check second preroll

So in VMAP you can set multiple prerolls (with or without bumbers) midrolls and postrolls and player tries all of them as a queue, (ad pods)

You can check VMAP standard document on http://www.iab.com/wp-content/uploads/2015/06/VMAP.pdf address

**Comment by vkdimitrov** [comment]
Excellent, thank you!

**Comment by andrewbecks** [comment]
Hi. This thread is very helpful, but I'm hoping I might be able to get some additional clarification from the original question: Does this plugin support VMAP/VAST/VPAID? Or does that require use of another plug-in? In the example docs, I see where you can setup ads manually, but I don't see any examples that leverage VMAP or VAST directly.

**Comment by incompl** [comment]
@andrewbecks This plugin does not support VMAP / VAST / VPAID directly.

**Comment by maroontr** [comment]
in where will i host to vmap file,please help?

**Comment by maroontr** [comment]
@hyurtseven81 in where will i host to vmap file,please help?
