### ISSUE TITLE
How to load  Video Only one time 

### ISSUE THREAD

**Issue by hridaya** [videojs/videojs-contrib-ads#118]
Hello,

Can we do like this with this plugin

When we change the video  content file through the resolution plugin  now advertise video play each time  but i need to skip ad each time ?   

So need to play first time when the  page loads and need to skip ad each time  the content video loads.

is that possible?

please help if possible

**Comment by incompl** [comment]
There is nothing in contrib-ads that specifically helps or hinders the scenario you describe. It would need to be built into your ad integration.
