### ISSUE TITLE
Fallback to another source on error after adstart

### ISSUE THREAD

**Issue by Mulder90** [videojs/videojs-contrib-ads#119]
I have a Vast VPAID that fails after adstart. Is possible to fallback on another source (I have a priority list of vasts) if an error occurs after adstart? Without having to pass to the state 'content-playback'

**Comment by se7entyse7en** [comment]
+1 for this

**Comment by incompl** [comment]
Great idea.

**Comment by incompl** [comment]
Looking back on this, I think the right way to do this is to stay in ad-playback while you fallback to a different VPAID. You could defer calling endLinearAdMode until the entire fallback process is complete.
