### ISSUE TITLE
Play button shown instead of loading spinner when resuming from ad

### ISSUE THREAD

**Issue by chemoish** [videojs/videojs-contrib-ads#123]
When an ad finishes `adend`, it loads the content `contentloadstart` (As expected).

However, **The time between these two states causes the play button to surface.**

![screen shot 2015-10-05 at 5 18 53 pm](https://cloud.githubusercontent.com/assets/549319/10297238/332919ee-6b85-11e5-93d3-b96a9a994ea1.png)

_This only is noticeable if the video requires an extended handshake_

This is caused because `player.load` fires the `loadstart` event and it hits `this.hasStarted(false)`.
SEE: https://github.com/videojs/video.js/blob/v4.12.15/dist/video-js/video.dev.js#L4084

What are the thoughts injecting `player.play()` after `player.load()` to force `firstplay`?

``` js
// if the src changed for ad playback, reset it
player.src({ src: snapshot.src, type: snapshot.type });
// safari requires a call to `load` to pick up a changed source
player.load();

player.play();

// and then resume from the snapshots time once the original src has loaded
player.one('contentcanplay', tryToResume);
```

SEE: https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.js#L318
SEE: https://github.com/videojs/video.js/blob/v4.12.15/dist/video-js/video.dev.js#L4081

Resulting in ad transitions utilizing a loading spinner.
![screen shot 2015-10-05 at 5 27 00 pm](https://cloud.githubusercontent.com/assets/549319/10297330/509f841c-6b86-11e5-974a-c78ad5c2a9ba.png)

**Comment by incompl** [comment]
I tried this out locally, and unfortunately it seems to result in two `playing` events when content resumes. I'm going to rename the issue after the root cause bug to reflect the fact that we would like to fix this, though this solution as-is would need additional effort.

**Comment by incompl** [comment]
Is this still an issue? I just tried to reproduce it and couldn't. Please reopen if it's still an issue.
