### ISSUE TITLE
ES6 import broken in 3.0.0?

### ISSUE THREAD

**Issue by nickygerritsen** [videojs/videojs-contrib-ads#124]
We are creating an extensive player based on video.js and we are using the 3.0 version of the ads plugin.

However since the dist directory has been removed, something strange is happening.

Because the `dist` directory is gone, we need to build the plugin ourselves (the .zip does not contain any dist files).

I use `grunt-subgrunt` for this, which can do this just fine.

However, now the ads plugin uses the "wrong" version of video.js: it uses the one from its own `node_modules`. It then registers its plugin on a `videojs` object that later gets overwritten by the real one.

We use browserify to create a final javascript file (similar to video.js itself) and I see that the ads plugin depends on the file with ID 97:

```js
},{}],96:[function(require,module,exports){
[...]
/**
 * Basic Ad support plugin for video.js.
 *
 * Common code to support ad integrations.
 */
},{"video.js":97}],97:[function(require,module,exports){
```

All my other code that uses `video.js` depends on a file with ID `95`, which is the correct `video.js` file.

If I copy the `videojs.ads.js` file from `node_modules/videojs-contrib-ads/dist` to e.g. `tmp` and include that one then everything works correctly.

If I remove the `video.js` directory from `node_modules/videojs-contrib-ads/node_modules` everything works too.

So it seems the video.js from the plugin overwrites the global one. I'm not sure how to fix this, because this is where my knowledge about this ends.

We are using ES6 style `import 'videojs-contrib-ads';` statements to import the plugin (and also all other code we need).

Hope anyone can help with this as we can now not build our code anymore.

**Comment by misteroneill** [comment]
That's definitely not desirable behavior! Are you installing `videojs-contrib-ads` via npm? It seems odd that the `dist` directory is not created; I just tested and it seems to work for me:

```
$ mkdir test && cd $_
$ npm i video.js@5.x.x videojs-contrib-ads@3.x.x
$ ls node_modules/videojs-contrib-ads/dist/
videojs.ads.global.js  videojs.ads.global.min.js  videojs.ads.js  videojs.ads.min.js
```

I don't see a `node_modules/videojs-contrib-ads/node_modules` directory created. Next, I set up a small test module and built it:

```
$ npm i babelify
$ vim index.js

import videojs from 'video.js';
import 'videojs-contrib-ads';

$ browserify index.js -t babelify -o bundle.js
```

I'm only seeing one copy of video.js bundled into `bundle.js`. This is on Node 0.12.7 and npm 2.11.3.

**Comment by nickygerritsen** [comment]
I'm not at my work pc anymore but I'll check when I'm there again what my package.json contains etc

**Comment by nickygerritsen** [comment]
For me, this happens:

```bash
$ mkdir test && cd $_
$ npm i video.js@5.x.x videojs-contrib-ads@3.x.x
[...]
$ ls node_modules/videojs-contrib-ads/dist/
ls: cannot access node_modules/videojs-contrib-ads/dist/: No such file or directory

$ npm version
{ http_parser: '1.0',
  node: '0.10.25',
  v8: '3.14.5.9',
  ares: '1.10.0',
  uv: '0.10.23',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1f',
  npm: '1.4.21' }
```

Maybe because of an really old npm?

**Comment by misteroneill** [comment]
I don't think it's npm. I tried using the same versions of Node/npm, but got the expected result - `node_modules/videojs-contrib-ads/dist` exists. :confused: 

On a side note, in case you weren't aware, NodeSource maintains [a PPA for Debian users](https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions), which has more Node/npm versions available.

**Comment by nickygerritsen** [comment]
Very strange then... I have no clue why we have different results.

**Comment by nickygerritsen** [comment]
After updating to the PPA it does work correctly btw.
