### ISSUE TITLE
And error occurs when using ads with videojs 5.0

### ISSUE THREAD

**Issue by vadikace** [videojs/videojs-contrib-ads#127]
Inside videojs.contrib.ads it tries to get and events in following line:
`videoEvents = videojs.Html5.Events`
which gives the following error:
`Cannot read property 'Events' of undefined`

**Comment by gkatsev** [comment]
The currently released version of contrib-ads isn't vjs 5 compatible, unfortunately. However, we have a PR for updates to get it working, if you want to give it a shot: https://github.com/videojs/videojs-contrib-ads/pull/121
It's also published on npm under the `next` tag (v3.0.0).

**Comment by vadikace** [comment]
@gkatsev Thanks 😃

**Comment by misteroneill** [comment]
PR #121 has been merged and a new minor version was released, `v3.1.0`, because a small feature was added.
