### ISSUE TITLE
vjs-5-upgrade freezes occasionally after endLinearAdMode()

### ISSUE THREAD

**Issue by oleynikd** [videojs/videojs-contrib-ads#129]
First of all - thank you for such a great tool!

I'm currently using `vjs-5-upgrade` branch with video.js v5.2.0 and video-js-swf v5.0.1
After `endLinearAdMode()` is called video occasionally freezes. About 1 per 50 calls.
Where should I look to see what's the problem? Maybe someone has the same issue?

Thanks.

**Comment by incompl** [comment]
Hi @oleynikd, glad to hear videojs-contrib-ads has been helpful for you! Sorry there was such a long delay before any response to your question. Is this still an issue for you?

**Comment by incompl** [comment]
Closing because it's very old, please reopen if still an issue.
