### ISSUE TITLE
Aborting video playback if a pre-roll fails

### ISSUE THREAD

**Issue by shawnbuso** [videojs/videojs-contrib-ads#130]
I had a publisher on our [IMA plugin ](https://github.com/googleads/videojs-ima) ask how they can abort content playback if a pre-roll fails to load ([issue here, see the most recent post](https://github.com/googleads/videojs-ima/issues/128)). Looking at the event flow chart, I don't know if this is possible. In my error handler I can do one of three things:
1. Fire adserror, which goes to content playback
2. Do nothing, which will lead to an eventual timeout and then content playback.
3. Fire adsready (even though they are not), which will result in readyforprerolll. From here I can:
   1. Fire adserror, which will lead to content playback.
   2. Fire adstart, which will enter ad playback mode.
   3. Do nothing, which will lead to an eventual timeout and then content playback.

Is there something I can do in my error handler to just tell the video player to stop everything and do nothing?

**Comment by tcctmw** [comment]
Any news?

**Comment by tcctmw** [comment]
Anyone?

**Comment by alouane** [comment]
Hi, you can try something like this:
player.error(code);
the code could be:
  1: 'You aborted the video playback',
  2: 'A network error caused the video download to fail part-way.',
  3: 'The video playback was aborted due to a corruption problem or because the video used features your browser did not support.',
  4: 'The video could not be loaded, either because the server or network failed or because the format is not supported.',
  5: 'The video is encrypted and we do not have the keys to decrypt it.'
you can add more if you want inside video.js...
and you can customize the vjs-error-display div for rendering ;)

**Comment by tcctmw** [comment]
This will completely block the player

The behavior I'd like to create is to pause (or better reset) the player if there isn't any ads or the ad throws an error

The player should AUTOSTART only in case everything ( preroll and content ) are correctly loaded

**Comment by alouane** [comment]
Well, to pause the video, you can simply do player.pause(); and for customization you can popup a message by calling player.error(your_custom_code); // this will not block the player, it just show a simple message
but i think you want to reset the ad not the player, no?

**Comment by tcctmw** [comment]
No. I want to reset the player

If the Ad it's loaded correctly, then play the Ad and then play the content
If the Ad loading fails, stop the content loading

**Comment by alouane** [comment]
but what is the next action to do after stopping the content loading? if you want juste to stop the video loading or downloading content you can change the player source: player.source(null);

**Comment by whatvn** [comment]
My guess is you want to reset (reload) the player so you're able to request a new ads if the current one is not available, if so, what you can do is keep requesting ads until you got ads that canPlay. is it possible?

**Comment by tcctmw** [comment]
@alouane I'll try this solution soon
@whatvn If the first attempt fails, I don't want to keep the player stuck waiting an ad to be loaded.
The player should reset as loaded without ads and without autoplay

Ad loaded correctly -> Autoplay ad and then autoplay content
Ad loading failed -> Player waiting to be started

**Comment by incompl** [comment]
Closing this conversation since there were some suggestions and I hope one panned out! Feel free to reopen if additional assistance is wanted.
