### ISSUE TITLE
videojs.getComponent is not a function

### ISSUE THREAD

**Issue by ankurhora** [videojs/videojs-contrib-ads#144]
Hi,

i am getting this error on line 9. Dont know how to resolve.
All code is in olace.. sorry new to al this

**Comment by gkatsev** [comment]
Sounds like you're using an incompatible version of videojs.
What versions of videojs-contrib-ads and videojs are you using? Can you post a reduced test case on a site like jsfiddle.net?

**Comment by ankurhora** [comment]
Thankyou for the reply.

Changed just after commenting and its working now :)

**Comment by gkatsev** [comment]
Well, happy to help :D 
Glad you got it working.

**Comment by ankurhora** [comment]
One last thing though.. Is it open source?
Can i use it for anything and not face any legal complications from google or whatsoever ?

**Comment by gkatsev** [comment]
Not sure exactly what you mean but this project is [licensed Apache 2.0](https://github.com/videojs/videojs-contrib-ads/blob/master/LICENSE-APACHE2)

**Comment by vjy13** [comment]
> Thankyou for the reply.
> 
> Changed just after commenting and its working now :)

What did you comment?
