### ISSUE TITLE
Any way to arrive at "preroll?" without first calling play?

### ISSUE THREAD

**Issue by shawnbuso** [videojs/videojs-contrib-ads#145]
We have an ima plugin user who is [asking how they can avoid showing a blip of content before their ad starts](https://github.com/googleads/videojs-ima/issues/178). I think this is caused by our call to play before we respond to the "preroll?" event. The player starts loading the content, then we tell it that we have a pre-roll, then it plays the pre-roll. Is there a way to arrive at the "adstart" event without calling play on the player so we can avoid loading the content until after the pre-roll plays?

**Comment by incompl** [comment]
I believe we're avoiding a content blip by hiding the video using CSS until we're done with the preroll. I don't believe you can arrive at preroll without calling play with this plugin.

**Comment by baqarrivi** [comment]
try to disable autoplay

**Comment by steevee** [comment]
The CSS we're using to hide the video-blip prior a __preroll__ ad is:

```sass
.vjs-ad-loading.vjs-playing, .vjs-ad-loading.vjs-waiting {
    // applied to element that contains the video
    .vjs-tech {
        display: none; 
    }
}
```
n.b. using only tested for preroll videos, and sound still plays momentarily.

**Comment by oldmtn** [comment]
Is this issue fixed now?
