### ISSUE TITLE
Caption/subtitle buttons are not hidden during an ad; user can re-enable captions from the main video during an ad

### ISSUE THREAD

**Issue by cdhowie** [videojs/videojs-contrib-ads#154]
Like the title says, if a text track is added to the player using `.addRemoteTextTrack()` and then an ad is played, the caption track is not removed from the player while the ad is playing.  If the viewer selects the caption track while the ad is playing, the captions for the main video show up on the ad.

**Comment by gkatsev** [comment]
We do disable the tracks when ads are playing but the button is still there for a user to click if the main control bar is being re-used. We probably should force the buttons to hide and re-show them after the ad is done.
In implementations around contrib-ads, what we've done is cloned the control-bar into a separate element that we use during ads and that control bar just never has the captions button.

**Comment by cdhowie** [comment]
We worked around this by simply removing all remote text tracks when an ad begins and re-adding them afterwards, so it's not a blocking issue currently.  This approach would not work (as easily) if we were using mid-rolls since it does not reselect the caption set the user had selected prior to the ad playing.

I'm confused by what you mean when you say that you do disable them -- do you mean that the code will effectively turn off captions when an ad begins, but the control bar will allow them to be re-enabled by the user?

If that's the case, then we may be able to solve this issue just by using the following CSS:

    .vjs-ad-playing .vjs-caption-settings {
        display: none;
    }

However, I'm concerned that simply disabling the active set and re-enabling it after the ad ends won't work when an ad itself has captions -- is that a use case that this plugin will someday be able to handle?

**Comment by gkatsev** [comment]
Yeah, we store the state of the captions before the ads and restore that state afterwards -- if a caption was selected before a midroll it will stay selected after the midroll. So, adding that piece of CSS should work for most cases. You'd probably want to select all the text track buttons (subtitles, captions, chapters, descriptions).
This doesn't work for when ads have captions themselves but we've rarely seen those, if at all.

**Comment by cdhowie** [comment]
Thanks for the clarification.  Seems I can remove a bunch of code -- always a good thing!

I wonder if this is something that should be documented in the readme so that developers know that this plugin doesn't itself hide the UI controls when an ad is playing.

**Comment by gkatsev** [comment]
We probably should just add the simple CSS that hides the text track buttons to this project by default.
Thoughts @misteroneill @dmlap @incompl?

**Comment by incompl** [comment]
Hiding the text tracks button during ads works for me, unless ads with captions proves to be a thing.

**Comment by gkatsev** [comment]
At that point, a lot more work will need to happen in this project anyway.

**Comment by incompl** [comment]
I made a PR for this https://github.com/videojs/videojs-contrib-ads/pull/211
