### ISSUE TITLE
Can not restore a player snapshot with m3u8 playlist on Android M + Chrome

### ISSUE THREAD

**Issue by apesant** [videojs/videojs-contrib-ads#173]
Hi,

I am trying to write an integration supporting Brightcove's playlists. When trying to play prerolls (in the readyforprerolls listener) on Android M, the following code is called:

```
// capture current player state snapshot (playing, currentTime, src)
            if (videojs.browser.IS_IOS || player.duration() !== Infinity) {
              this.snapshot = getPlayerSnapshot(player);
            }
```

`player.duration()` returns Infinity so no snapshot is saved. When trying to exit ad mode after the postrolls, `restorePlayerSnapshot` is called, with an empty snapshot:

```
restorePlayerSnapshot = function(player, snapshot) {
    if (player.ads.disableNextSnapshotRestore === true) {
      player.ads.disableNextSnapshotRestore = false;
      return;
    }
    var
      // the playback tech
      tech = player.$('.vjs-tech'),

      // the number of remaining attempts to restore the snapshot
      attempts = 20,

      suppressedTracks = snapshot.suppressedTracks, //snapshot is undefined
      trackSnapshot,
      restoreTracks =  function() {
        var i = suppressedTracks.length;
        while (i--) {
          trackSnapshot = suppressedTracks[i];
          trackSnapshot.track.mode = trackSnapshot.mode;
        }
      },
```

This happens on Android M using Chrome 50 on a Nexus 6P.

**Comment by incompl** [comment]
What a coincidence that you opened this issue today! I am actually working on a fix for this very issue. Expect to see a fix soon.

**Comment by incompl** [comment]
I have a proposed solution in a pull request: https://github.com/videojs/videojs-contrib-ads/pull/174

I'd like to test it some more. In the meantime, if you could try it out and see if it fixes your issue that would be a big help.

**Comment by apesant** [comment]
Just tried it and it works on my device, cool!

**Comment by incompl** [comment]
Excellent! This fix will be included in the next contrib-ads release.

**Comment by oleynikd** [comment]
I have similar issue with Preroll and Live HLS. Error when trying to `ads.endLinearAdMode()`:
`Uncaught TypeError: Cannot read property 'suppressedTracks' of undefined`

**Comment by incompl** [comment]
This issue has been fixed. @oleynikd if you are still seeing an bug please open a new issue.
