### ISSUE TITLE
Play ads without video content

### ISSUE THREAD

**Issue by Dracoborg** [videojs/videojs-contrib-ads#178]
Hi, 
Is there a possibility to play ads with this plugin without any video content. In my case I do not provide any video content. Also to prevent error from videojs preload attribute is set to false. Then I load vast document and parse them. When adsready event is set nothing happend because no content-set state happend. I do want to use this plugin because I would like to use this player to play prerolls, midrolls and postrolls in some cases. Any Idea how to make it possible without errors in console (neither from videojs-ads-contrib nor videojs itself)

**Comment by incompl** [comment]
Most of what videojs-contrib-ads does is coordinate ad and content playback. I don't think it would be helpful for the use case you're suggesting.
