### ISSUE TITLE
import with webpack/babel

### ISSUE THREAD

**Issue by eric7578** [videojs/videojs-contrib-ads#185]
trying to import this module into my project. I tried the following two ways of import

`import 'videojs-contrib-ads'`
`import 'videojs-contrib-ads/dist/videojs.ads.js'`

yet, this ERROR pop up.

`ERROR in ./~/videojs-contrib-ads/dist/videojs.ads.js
Module not found: Error: Cannot resolve module 'videojs'`

Provided is my version of this pluing 
`videojs-contrib-ads": "^3.3.12"`

**Comment by qpre** [comment]
Any plans on making it easier to integrate ? `grunt-umd` seems to export the plugin in a really non conventional way.

**Comment by gkatsev** [comment]
I think ultimately what we'd want is to remove our custom UMD wrapper and switch to using browserify to build out the `dist/` file while keeping the main file requireable for webpack/browserify like we are doing in videojs and the other contrib projects.

**Comment by mkhazov** [comment]
For now this worked for me:

`import 'videojs-contrib-ads/src/videojs.ads';`

**Comment by eric7578** [comment]
@gkatsev 
thanks for the reply and the team effort!

@mkhazov 
I will try it later! thanks!

**Comment by incompl** [comment]
The way this project is built and package will be updated to follow the conventions set forth in [generator-videojs-plugin](https://github.com/videojs/generator-videojs-plugin) in the upcoming 4.0 release.

**Comment by incompl** [comment]
Version 4 is out. Please reopen if this issue is seen with any 4.x.x versions!
