### ISSUE TITLE
Black placeholder div covers pre-roll ad on iOS.

### ISSUE THREAD

**Issue by bcharna** [videojs/videojs-contrib-ads#191]
The function `cancelContentPlay` in videojs.ads.js contains a block of code that inserts a black placeholder div over the player:

```
    // Avoid content flash on non-iPad iOS
    if (videojs.browser.IS_IOS) {

      var width = player.currentWidth ? player.currentWidth() : player.width();
      var height = player.currentHeight ? player.currentHeight() : player.height();

      // A placeholder black box will be shown in the document while the player is hidden.
      var placeholder = document.createElement('div');
      placeholder.style.width = width + 'px';
      placeholder.style.height = height + 'px';
      placeholder.style.background = 'black';
      player.el_.parentNode.insertBefore(placeholder, player.el_);

      // Hide the player. While in full-screen video playback mode on iOS, this
      // makes the player show a black screen instead of content flash.
      player.el_.style.display = 'none';

      // Unhide the player and remove the placeholder once we're ready to move on.
      player.one(['adplaying', 'adtimeout', 'adserror', 'adscanceled', 'adskip',
                  'contentplayback'], function() {
        player.el_.style.display = 'block';
        placeholder.remove();
      });
    }
```

I am using the videojs-ima plugin by Google (https://github.com/googleads/videojs-ima) and the black placeholder div stays on top of the ad the entire time because the videojs-ima plugin doesn't trigger an `adplaying` event. Ideally the Google plugin should trigger that event, but I think either this is a bug in videojs-contrib-ads, or the docs should mention that the firing of this event by the plugin is mandatory.

**Comment by incompl** [comment]
I apologize for this oversight: I did not realize that other integrations might not send adplaying. I am going to add this to the README because at the moment it is required. I am also going to think about if there is a way to make this work without that.

**Comment by sonicsoul** [comment]
Could somebody help me with the same issue?
I am actually wondering where to put which code to make that work.. 

Also I would like to know, which combination of videojs,contrib-ads and ima sdk works best. Any suggestions here? 

Thank you,
Steve

**Comment by sonicsoul** [comment]
Ah, I think I just found it. 
I placed  "this.player.trigger('adplaying'); " inside the videojs.ima.js function "onAdStarted_" 
and things seem to work as intended now.. sry it´s an ima issue I am discussing here..
