### ISSUE TITLE
npm install and build not working

### ISSUE THREAD

**Issue by jrglass** [videojs/videojs-contrib-ads#194]
Updated to latest version of Node.js and npm.
After running npm install within the videojs-contrib-ads-master directory I get a bunch of warnings and directions to contact the plugin author with error log.

Any ideas why this is happening?
npm-debug-log attached.

Tell the author that this fails on your system: 
npm ERR!     npm-run-all -p build:*

[npm-debug.log.txt](https://github.com/videojs/videojs-contrib-ads/files/512024/npm-debug.log.txt)

**Comment by gkatsev** [comment]
Can you post the output of `npm ls --depth=0`?

**Comment by jrglass** [comment]
videojs-contrib-ads@3.3.13 /Users/jrglass/Downloads/videojs-contrib-ads-master
├── babel-cli@6.16.0
├── babel-plugin-transform-object-assign@6.8.0
├── babel-preset-es2015@6.16.0
├── babelify@7.3.0
├── bannerize@1.1.2
├── bluebird@3.4.6
├── browserify@12.0.2
├── browserify-shim@3.8.12
├── browserify-versionify@1.0.6
├── budo@8.4.0
├── bundle-collapser@1.2.1
├── es5-shim@4.5.9
├── ghooks@1.3.2
├── glob@6.0.4
├── global@4.3.1
├── grunt@0.4.5
├── grunt-cli@0.1.13
├── grunt-contrib-clean@0.4.1
├── grunt-contrib-concat@0.3.0
├── grunt-contrib-connect@0.8.0
├── grunt-contrib-copy@0.8.2
├── grunt-contrib-jshint@0.6.5
├── grunt-contrib-qunit@0.2.2
├── grunt-contrib-uglify@0.2.7
├── grunt-contrib-watch@0.4.4
├── grunt-umd@2.3.6
├── karma@0.13.22
├── karma-chrome-launcher@0.2.3
├── karma-detect-browsers@2.1.0
├── karma-firefox-launcher@0.1.7
├── karma-ie-launcher@0.2.0
├── karma-qunit@0.1.9
├── karma-safari-launcher@0.1.1
├── load-grunt-tasks@3.5.2
├── lodash@3.10.1
├── mkdirp@0.5.1
├── node-sass@3.10.1
├── npm-run-all@1.8.0
├── qunitjs@1.23.1
├── rimraf@2.5.4
├── sinon@1.14.1
├── uglify-js@2.7.3
├── video.js@5.11.7
└── videojs-standard@4.0.3

npm ERR! extraneous: abbrev@1.0.9 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/abbrev
npm ERR! extraneous: ansi-styles@2.2.1 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/ansi-styles
npm ERR! extraneous: aproba@1.0.4 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/aproba
npm ERR! extraneous: are-we-there-yet@1.1.2 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/are-we-there-yet
npm ERR! extraneous: asn1@0.2.3 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/asn1
npm ERR! extraneous: assert-plus@0.2.0 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/assert-plus
npm ERR! extraneous: is-fullwidth-code-point@1.0.0 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/babel-cli/node_modules/chokidar/node_modules/fsevents/node_modules/is-fullwidth-code-point
npm ERR! extraneous: abbrev@1.0.9 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/abbrev
npm ERR! extraneous: ansi-styles@2.2.1 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/ansi-styles
npm ERR! extraneous: aproba@1.0.4 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/aproba
npm ERR! extraneous: are-we-there-yet@1.1.2 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/are-we-there-yet
npm ERR! extraneous: asn1@0.2.3 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/asn1
npm ERR! extraneous: assert-plus@0.2.0 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/assert-plus
npm ERR! extraneous: is-fullwidth-code-point@1.0.0 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/budo/node_modules/chokidar/node_modules/fsevents/node_modules/is-fullwidth-code-point
npm ERR! invalid: noptify@0.0.3 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/grunt-contrib-watch/node_modules/tiny-lr/node_modules/noptify
npm ERR! extraneous: nopt@2.0.0 /Users/jrglass/Downloads/videojs-contrib-ads-master/node_modules/grunt-contrib-watch/node_modules/nopt

**Comment by gkatsev** [comment]
I've just tried it locally and it worked for me. Not exactly sure what could be the problem. Maybe the extraneous or invalid modules are causing an issue? I would consider deleting `node_modules` and trying again. Maybe even clearing the cache.

**Comment by jrglass** [comment]
Yup, that did it.
Not sure what that folder was but we are good to go.
Thanks!

**Comment by gkatsev** [comment]
Ah nice. Yeah, sometimes the old "turn it off and on again" works even for stuff like node_modules :)
