### ISSUE TITLE
triggers the start and end ?? plugin does not work

### ISSUE THREAD

**Issue by surikat1978** [videojs/videojs-contrib-ads#201]
this framework does not work. If you insert example, nothing happens.
In Firefox the error immediately, but in chrome seems to partially work, but not working all events.
there examples very differently done, and it works.
it is unclear the meaning of this framework, triggers the start and end are run manually, and the rest.
 For Example :  http://a.kaniztra.com/ad/index.html

**Comment by incompl** [comment]
The core message of your comment seems to be that this framework is difficult to use and understand. I understand where you're coming from. We will continue our efforts to improve the ease-of-use of this tool.
