### ISSUE TITLE
Time display when ad playing

### ISSUE THREAD

**Issue by viasors** [videojs/videojs-contrib-ads#222]
Hi, is any solution how to display currentTime in the original CurrentTimeDisplay component? Since 'timeupdate' event is blocked by 'adtimeupdate'?

**Comment by viasors** [comment]
I can do display update with hack below. Does a better solution exist?

```
player.on('adtimeupdate', function() {
	this.controlBar.getChild('CurrentTimeDisplay').updateContent();
});
```

**Comment by incompl** [comment]
That seems fine. Some ad integrations create their own control bar that
updates itself, that's why this is not a default behavior.

**Comment by viasors** [comment]
This was working by default with vjs 4.x or am I wrong?

As you said, own progress bar seems to be the cleanest solution in this case...

**Comment by incompl** [comment]
I don't believe this behavior has changed, but I could be wrong.

**Comment by viasors** [comment]
I think we can close this issue.
