### ISSUE TITLE
Flash of content on play

### ISSUE THREAD

**Issue by bcharna** [videojs/videojs-contrib-ads#242]
I am using google videojs-ima (master) in conjunction with this library (4.2.3). Upon clicking play, I see a bit of content flash before the preroll starts. I am using playsinline on iOS 10. I am able to experience less occurrences of flash if I change this line of code:
https://github.com/videojs/videojs-contrib-ads/blob/master/src/cancelContentPlay.js#L21.
I change the check to `player.el_.hasAttribute('playsinline')` instead of `!player.el_.hasAttribute('playsinline')`. I also see the above comment has "...iPhones on iOS10 with playsinline" which makes it peculiar that there would be a negation in the check. May I be missing something?

With that change, most of the time there is no flash but still on some attempts there is a tiny bit of a content flash. Without the change, however, the flash happens consistently.

Final note that I modified google videojs-ima to trigger an "adstart" event, per the discussion at https://github.com/videojs/videojs-contrib-ads/issues/191. Now I am just trying to update all the libraries and want to get a solid playback experience.

**Comment by incompl** [comment]
Hi @bcharna, this is because the existing content flash prevention code breaks the player with iOS10 and playsinline. An adapted  / new solution that works with IOS10 and playsinline has not yet been developed.
