### ISSUE TITLE
Any examples for a functioning setup with vast-xml files?

### ISSUE THREAD

**Issue by martinstender** [videojs/videojs-contrib-ads#247]
Hi all

I'm really struggling to get a working setup running.
I had no problems getting 'videojs-vast-vpaid' working, but that only supports prerolls as of now, and since we need pre- and postrolls, 'videojs-contrib-ads' seems like the right choice.

But as far as I understand, 'videojs-contrib-ads' needs another plugin to handle the actual loading and parsing of vast xml-files... is that correct?

Is there a guide or an example where I can see a working setup with a preroll and perhaps a postroll loading ads from a vast file?

Thanks in advance :-)

**Comment by martinstender** [comment]
Also - although I assume the developers of this plugin would like not to step on anyones toes - is there a vast-plugin that is recommended more than other ones?

**Comment by adamellsworth** [comment]
I'm working on this as well and I'm not aware of a supplemental plugin to get VAST to work.

Ideally, you would just use want to use `DOMParser`:

__my-vast-conf.js__
```js
module.exports = '<?xml version="1.0"?><vmap:VMAP .......', 
```



```js
var vastConf = require('./my-vast-conf.js')
var d = new DOMParser();
var parsed = d.parseFromString(vastConf, "text/xml");

```

**Comment by incompl** [comment]
You're correct that this plugin isn't a standalone solution, but rather is a technical framework that a complete solution would be built on top of. If you want something that plays ads out of the box with no development, this isn't the right project.

**Comment by steevee** [comment]
Try https://github.com/googleads/videojs-ima - checkout out the `adTagUrl` option.
