### ISSUE TITLE
Skip preroll, play content and still play postroll

### ISSUE THREAD

**Issue by martinstender** [videojs/videojs-contrib-ads#249]
Hi

I'm implementing the videojs-contrib-ads plugin, and got most things running.
But I would like a skip-ad btn, so I create one after 5000 ms, but can't figure out what function to call, when I want to skip the remainder of the ad and play the content.
if I call endLinearAdMode, the content plays, but then the postroll doesn't run...

Suggestions?

**Comment by mimcz** [comment]
Hi, have you tried `player.currentTime(player.duration());` ?

**Comment by elisamuell** [comment]
Have you tried player.ads.endLinearAdMode();???
I'm working on a skip button, could you help me with your code, tips, ideas ...? Thanks

**Comment by mimcz** [comment]
I did the skipButton pretty simple. This is the click handler:
```
function skipAdFn(e) {
    e.preventDefault();
    // to handle skip tracking
    player.trigger('ads-skip');
    // Let other tracking (like midpoint/complete) know that this spot was skiped
    currentAd.skiped = true
    // skip to the end of spot
    player.currentTime(player.duration());
}
```
Right after there is `adended` event which you can use to remove event listeners and `player.ads.endLinearAdMode()` or to play next spot in the break. Mine looks something like this:
```
function adEndedFn() {
    // remove spot-specific event handlers
    adui.adLink.off('click');
    adui.adSkipBtn.off('click');
    player.off('adtimeupdate', trackAdProgressFn);
    player.trigger('ads-ad-ended');

    // check if there is another ad in break to play
    if (state.inventory[nextAd]) {
        nextAd();
    } else {
        player.off('adended', adEndedFn);
        // back to content
        player.ads.endLinearAdMode();
    }
}
```

I also did skip countdown function in use with `adtimeupdate` event. I used to did it with `setTimeout` but the coundown was running even if user paused the ad.
```
function skipCountDownFn() {
    const time = Math.floor(player.currentTime());
    const skipIn = currentAd.creative.skipDelay - time;
    if (skipIn > 0) {
        // update UI
        adui.adSkipBtn.updateText('Skip in ' + skipIn + 's');
    } else {
        // Stop the count down
        player.off('adtimeupdate', skipCountDownFn);
        // update UI
        adui.adSkipBtn.on('click', skipAdFn);
        adui.adSkipBtn.updateText('Skip Ad');
    }
}
```
Hope this helps :)

**Comment by thangnm1610** [comment]
Dear mimcz.
May u post full code about skip preroll? thanks u very much
