### ISSUE TITLE
adsready cannot be triggered on the same event loop cycle as contentupdate

### ISSUE THREAD

**Issue by cdhowie** [videojs/videojs-contrib-ads#261]
The documentation has this example for handling the `contentupdate` event:

```
player.on('contentupdate', function(){
  // fetch ad inventory asynchronously, then ...
  player.trigger('adsready');
});
```

In our case, the ad information is delivered as part of the video metadata payload, so we don't actually have to wait.  Our code was pretty much exactly what's above.  Somewhere between video.js 5.4.6 and video.js 5.19.2, and/or the -ads plugin (from around 5.4.6) and the current version, this no longer works and causes the player to hang indefinitely.  (Disclosure: We are also using the video.js HLS plugin.)

The solution was as simple as:

```
player.on('contentupdate', function(){
  setTimeout(function () {
    player.trigger('adsready');
  }, 0);
});
```

I'm not sure if it's a code bug that it's even required to delay triggering this event until a future turn of the event loop, or a documentation bug that fails to mention that it's required to do so.  The comment "fetch ad inventory asynchronously" does subtly imply that normally you *would* wind up firing this event on a future turn of the event loop, but it in no way indicates that this is required for correct functionality.

**Comment by adamellsworth** [comment]
I believe this bit of time-magic is the culprit:

https://github.com/videojs/videojs-contrib-ads/blob/020322d6d9e6d5a4098b43fe50fefa24c997d573/src/contentupdate.js#L35

**Comment by incompl** [comment]
We are planning improvements around source changing using new features in VJS6, for now this is sadly a limitation in the plugin.
