### ISSUE TITLE
Choppy playback of HSL when content-resuming is triggered

### ISSUE THREAD

**Issue by martinstender** [videojs/videojs-contrib-ads#263]
Hi all

I'm struggling to get the main-content to resume smoothly, after a preroll as ended.
I have a simplified codepen here, where the sources for the pre- and postrolls are hardwired.

https://codepen.io/martinstender/pen/KmLLxV?editors=0011

If you set playAds to `false` on line 18, all is good, but when it is set to `true`, and a preroll has ended, I get a 3-5 second stall, before the main-content starts playing.

I had a conversation on Slack with Garrett Singer, contributor to the contrib-hsl plugin, and he has a theory, that it may have to do with the currentTime being larger than 0 when the main source is set and the player then seeks back to zero, and reloading the sources... 
But setting `player.currentTime(0)` before calling `player.ads.endLinearAdMode()`, doesn't help, I'm afraid.

Any ideas?

Many thanks in advance 😄

**Comment by incompl** [comment]
Hi @martinstender, thanks for taking the time to make a codepen, that really helps figure out what's going on. I'd like to dig in, but I'm seeing this error:

```
pen.js:122 Uncaught TypeError: player.ads is not a function
    at b.<anonymous> (pen.js:122:14)
    at b.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/video.js/6.0.0/video.min.js:12:13485)
    at Array.forEach (native)
    at b.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/video.js/6.0.0/video.min.js:12:13463)
    at e (https://cdnjs.cloudflare.com/ajax/libs/video.js/6.0.0/video.min.js:18:23832)
```

Let me know if I'm doing something wrong or if you've updated it and I'll take another look.

**Comment by martinstender** [comment]
Hi @incompl 

Adblocker?  :-)

**Comment by incompl** [comment]
@martinstender Doh, yup.

That stall is interesting. I would agree that HLS would be the first place I'd look for answers too. Does it happen with other content videos?

**Comment by martinstender** [comment]
If you try to swap the two sources, all is good - and of course, if there is no preroll. Strange...

**Comment by incompl** [comment]
@martinstender I don't believe you're using contrib-ads wrong because your example works great when I swap in a different m3u8. Would you be open to re-encoding the content?

**Comment by martinstender** [comment]
Aboslutely. I just can't do it right now, but tomorrow morning (Copenhagen time, which should be 6 hours ahead of Boston).
But it is amazon elastic transcoder with 10 second segments and some 3 or 4 different sizes/bitrates.
The HLS you are having success with, do you know how that is transcoded?

Thank you for your help :-)

**Comment by martinstender** [comment]
Or maybe I should look into showing the ads on top of the main player...?

**Comment by incompl** [comment]
You can do that too, it just doesn't work on iOS when content isn't played inline (only supported in iOS10+). Plugins that show ads on top of the player generally still share the content element on iOS.

**Comment by martinstender** [comment]
The reason other m3u8 works better, is that they are demuxed. 
Unfortunately we are stuck on HLSv3 as of now, so we can't create playlists that contain video-only and audio-only .ts's.

It's actually a bit weird, because I have seen HLSv3 playlists 'out there', that contains demuxed .ts's, but Amazon Elastic Transcoder doesn't allow HLSv3 playlists with video-only and audio-only presets...

Maybe I should take this issue to either the contrib-hls team or maybe the videojs team?

**Comment by incompl** [comment]
Very interesting. Yeah, I'd ask the folks working on contrib-hls for this one.

**Comment by martinstender** [comment]
I just did  - hoping for some good input.

Btw, I can skip playing an ad all the way through, by calling `player.trigger('adended')`.
But that obviously end up sending an `adended` event to the advertiser in my full implementation, which would be misleading.

Skipping a preroll and sending an 'adclosed'-ish event (without calling `skipLinearAdMode`) - is that somehow missing?

Best regards :-)

**Comment by incompl** [comment]
Regarding skipping ads with adended: since this is a client-side library, it's always possible to do adblock-type techniques to skip ads. Server side ads are the only solution to this.

If an ad is being ended, even if it's due to user interaction, you'll still want to use endlinearadmode. We don't use a separate API for different reasons a linear ad has ended.

**Comment by martinstender** [comment]
Oh, I was talking about `skipLinearAdMode` not `endLinearAdMode` - but that's really another topic.
But I just heard back from the good people at contrib-hls, and they sent me back here... 

The theory is this: 
> contrib-ads might be seeking as it restores the state, thereby clearing the buffer after contrib-hls may have started playing, leading to a stall as it reloads content.

if that sounds the least bit plausible, is there anything I can do myself?

Best regards
Martin

**Comment by incompl** [comment]
You could investigate that theory by looking at player events, here is some code you could use to get a lot of relevant events to log out:

```
var events = ['play', 'playing', 'loadstart', 'ended', 'suspend', 'abort', 'error',
'emptied', 'stalled', 'loadedmetadata', 'loadeddata', 'canplay', 'canplaythrough',
'waiting', 'seeking', 'durationchange', 'timeupdate', 'progress', 'pause', 'ratechange',
'volumechange', 'firstplay', 'suspend'];
events = events.concat(events.map(function(e) {return 'ad' + e;}));
events = events.concat(events.map(function(e) {return 'content' + e;}));
videojs.players.vjs_video_3.on(events, function(e) {videojs.log('EVENT: ' + e.type);});
```

**Comment by martinstender** [comment]
Clever - many thanks :-)

**Comment by martinstender** [comment]
Ok - here is the interesting part of that log:

After `adend` I set a timer (skipping `timeupdate` and `progress` events)

```
"VIDEOJS:" "EVENT: adtimeupdate -> 4.195s" <-- last adtimeupdate before I skip ad by trigging 'adend'
"VIDEOJS:" "EVENT: adended -> 4.288s"
"adended trigged - set timer --------------"
"VIDEOJS:" "EVENT: contentabort -> 0.02s"
"VIDEOJS:" "EVENT: contentemptied -> 0.02s"
"VIDEOJS:" "EVENT: contentabort -> 0.05s"
"VIDEOJS:" "EVENT: contentemptied -> 0.05s"
"VIDEOJS:" "EVENT: contentloadstart -> 0.079s"
"VIDEOJS:" "EVENT: contentfirstplay -> 0.08s"
"VIDEOJS:" "EVENT: contentplay -> 0.08s"
"VIDEOJS:" "EVENT: contentwaiting -> 0.081s"
"VIDEOJS:" "EVENT: contentdurationchange -> 0.086s"
"VIDEOJS:" "EVENT: contentloadedmetadata -> 0.278s"
"VIDEOJS:" "EVENT: contentloadeddata -> 0.316s"
"VIDEOJS:" "EVENT: contentcanplay -> 0.317s"
"VIDEOJS:" "EVENT: playing -> 0.319s"
"VIDEOJS:" "EVENT: canplaythrough -> 0.32s"
"VIDEOJS:" "EVENT: seeking -> 0.327s"
"VIDEOJS:" "EVENT: waiting -> 0.331s"
"VIDEOJS:" "EVENT: canplay -> 0.945s"
"VIDEOJS:" "EVENT: playing -> 0.945s"
"VIDEOJS:" "EVENT: canplaythrough -> 0.946s"
"VIDEOJS:" "EVENT: stalled -> 4.256s"
"VIDEOJS:" "EVENT: pause -> 4.268s" <- pausing here - but at this point, video plays fine
```

(codepen is here: https://codepen.io/martinstender/pen/BZaKaR?editors=0011 )

So the `playing` at .945 just plays the audio - the video picks up at 4.256 when `stalled` shows in the log. Strange, since the source is muxed...

(Again, disabling ads at line 18 makes the problem go away)

Best regards

**Comment by incompl** [comment]
Hi there, sorry I didn't follow up on this issue. If there is still an issue please reopen and I can help.
