### ISSUE TITLE
Ads are not Working on Android (web)

### ISSUE THREAD

**Issue by maryam-abdullah** [videojs/videojs-contrib-ads#265]
Hello,
I'm using Google ads and it works fine on PCs.
However on mobile (web), I get this error:

> Ad error: AdError 1005: The provided ad type: skippablevideo is not supported. (videojs.min.js)

```
<script type="text/javascript">
                    var player = videojs('videojs');
                    var options = {
                        id: 'videojs',
                        adTagUrl: '@Html.Raw(adTemp.Id)'
                    };
                    player.ima(options);
                    player.ima.requestAds();
                    player.ima.initializeAdDisplayContainer();
                    player.play();
</script>
```

Thanks.

**Comment by incompl** [comment]
This is a limitation of Google's IMA SDK. There is some more information in this thread: https://groups.google.com/forum/#!msg/ima-sdk/jYE6j4_YCko/m6HuIkM9uKMJ

**Comment by maryam-abdullah** [comment]
Okay.
So what should I use instead?
I'm using a VAST XML, and video with m3u8 extension.
Do you suggest using videojs-vast-plugin or videojs-vast-vpaid in order to work both on Mobile and PC.

Thanks.

**Comment by incompl** [comment]
I believe the limitation is because the "skip" button cannot be rendered over the video on those platforms, so it's a technical restriction. Maybe IMA is extra strict in rejecting the ad outright due to being skippable, in which case another project might be more lenient, but I'm not sure.

**Comment by incompl** [comment]
However, if you're still using Google IMA SDK, using a different Video.js integration will not change the behavior.

**Comment by maryam-abdullah** [comment]
Yeah, I see.
Look what I found:
> If a skippable ad is returned over a VAST redirect, DFP will not track skip-related VAST metrics.

I'm actually using VAST ad, so the best option was to disable the skippable option.
Thanks.
