### ISSUE TITLE
How to read VAST file from videojs-contrib-ads

### ISSUE THREAD

**Issue by sgromkov** [videojs/videojs-contrib-ads#268]
Hello!

Faced with the task: I should read a VAST file, and if there is a custom `<Extension type="linkTxt">` display the custom element with reached text over the advertising. ([Vast file custom extensions screenshot](http://joxi.ru/DrlOlxySvEZ97A)).

I figured out how to create my own elements on top of advertising.

Could you give me some advice how to get the content of the VAST file, to pull out of it my extension value?

**Comment by incompl** [comment]
If you're doing it yourself, the process is the same as fetching any XML file from a server and parsing the contents. You might use XMLHttpRequest directly, or a library like jQuery if you're using one.

If you're using a 3rd party SDK that is responsible for fetching and reading the VAST file, you'll need to look at the API docs for that SDK and see if the information you need is exposed.

Hope this helps!

**Comment by sgromkov** [comment]
Thank you, incompl!

**Comment by incompl** [comment]
Happy to help!
