### ISSUE TITLE
contentupdate not firing

### ISSUE THREAD

**Issue by adamellsworth** [videojs/videojs-contrib-ads#271]
__Dependency Versions:__
```
"react": "^15.5.4",
"video.js": "^6.1.0",
"videojs-contrib-ads": "^5.0.1",
"videojs-contrib-hls": "^5.7.0",
"videojs-contrib-quality-levels": "^2.0.3"
```

I'm not sure if this is a bug, but it's got the slack channel stumped (as of yet anyway).

My player setup works fine (HLS).

```jsx
import React, { Component } from 'react';
import videojs from 'video.js';
import ads from 'videojs-contrib-ads';
import * as HLS from 'videojs-contrib-hls';
import 'video-js.css';

export default class extends Component {
    constructor (props) {
        super(props);
        this.player = null;
        this.handleSetup = this.handleSetup.bind(this);
    }

    handleSetup () {
        // ..., returns valid `sources` array
    }

    componentDidMount () {
        this.player = videojs(
            this.videoNode,
            this.handleSetup(),
            function onPlayerReady () {
                var player = this;
                player.ads({
                    playPreroll: true,
                    debug: true
                });

                // Triggered
                console.log('onPlayerReady');

                player.on('contentupdate', function () {
                    // Never triggered
                    console.log('contentupdate');
                    player.trigger('adsready');
                });

                player.on('readyforpreroll', function () {
                    // Never triggered
                    console.log('readyforpreroll');
                    player.ads.startLinearAdMode();
                    player.src("https://our.ad-server.com/some-unique-ad.mp4");
                    player.one('adended', function() {
                        console.log('adended');
                        player.ads.endLinearAdMode();
                    });
                });

                
                // For logging/debugging purposes
                var evs = [
                    'adtimeout',
                    'contentplayback',
                    'adsready',
                    'adstart',
                    'adend',
                    'adskip',
                    'timeupdate'
                ];

                evs.map(function (ev) {
                    player.on(ev, function () {
                        console.log('[PLAYER LOG]: %s', ev)
                    });
                });
            }
        );
    }

    render () {
        return (<div data-vjs-player>
            <video ref={node => this.videoNode = node} className="video-js vjs-16-9">
            </video>
        </div>);
    }
}
```

In the console I'm seeing the following log:
```
VIDEOJS: ads play triggered: content-set -> ads-ready?
[PLAYER LOG]: contentplayback
VIDEOJS: ads adtimeout triggered: ads-ready? -> content-playback
[PLAYER LOG]: adtimeout
[PLAYER LOG]: timeupdate
```

**Comment by incompl** [comment]
This appears to be the behavior you get when ad plugin initialization happens too late. [More information here](https://github.com/videojs/videojs-contrib-ads#important-note-about-initialization)

**Comment by incompl** [comment]
Also, in 2.19.0, we added an error message when the ad plugin is initialized late. Are you using 2.19.0+ and are you seeing that error in the browser dev console?

**Comment by adamellsworth** [comment]
No that error msg doesn't display.

**Comment by adamellsworth** [comment]
No that error msg doesn't display. And yeah, using `"videojs-contrib-ads": "^5.0.1",`. I updated the original comment with more info.

**Comment by marinacassiolli** [comment]
I'm having a similar problem in my rails project, but my console fires the warning like @incompl told above:

"VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect"

But my code seems correct:

```
video = videojs('video-<%= @content.id %>', {}, function() {
    var player = this;
    player.ads({ debug: true });
});
```

And my application.js.coffee is something like this:
```
#= require video
#= require videojs.ads
```

I'm using
The videojs_rails (gem) 5.4.6 
Videojs-contrib-ads 5.0.1

Any idea what's going on?

**Comment by incompl** [comment]
@marinacassiolli By initializing the plugin in the callback, you're effectively doing the same thing: the callback is not called until player ready. Try something like this:

    video = videojs('video-<%= @content.id %>', {});
    video.ads({ debug: true });

**Comment by marinacassiolli** [comment]
@incompl you're completely right, it's working now! Thanks a lot!

**Comment by incompl** [comment]
@marinacassiolli Great to hear!

@adamellsworth Did you try the same thing?

**Comment by adamellsworth** [comment]
I did to no avail. I'm stepping through the plugin to see where the hangup is now.
