### ISSUE TITLE
Support pause preroll programmatically

### ISSUE THREAD

**Issue by foisonocean** [videojs/videojs-contrib-ads#274]

**Comment by incompl** [comment]
The ad integration integration that uses this library rather than contrib-ads itself would be responsible for ad playback / pausing between startLinearAdMode and endLinearAdMode. The logic for handling pause would be in there.

**Comment by foisonocean** [comment]
@incompl  Can you show me a small example? I want to pause the ad when the client receive a message pushed from server.

**Comment by incompl** [comment]
It would depend a lot on how your integration works. It might be useful to look at how the Google IMA Video.js plugin does it, since it uses this library: https://github.com/googleads/videojs-ima/search?utf8=%E2%9C%93&q=pause&type=
