### ISSUE TITLE
VideoJS 6 Support?

### ISSUE THREAD

**Issue by treyhoover** [videojs/videojs-contrib-ads#275]
Is this plugin compatible with videojs 6? I haven't been able to get it working yet.

**Comment by gkatsev** [comment]
Yes, it is supported. Are you seeing any particular errors? What versions of videojs and contrib-ads are you using?

**Comment by treyhoover** [comment]
Hm, yeah. I'm using videojs 6.1.0 and contrib-ads 5.0.3. The error I'm seeing is:

`index.js:17 Uncaught TypeError: player.ads is not a function`

**Comment by gkatsev** [comment]
That's weird. How are you bundling the player? Do you have a live reduced test case?

**Comment by incompl** [comment]
This could be due to an adblocker. Is this still an issue?

**Comment by incompl** [comment]
Haven't heard anything back, so closing this issue. Feel free to reopen or open a new issue if you're still having trouble.
