### ISSUE TITLE
Player.ads is not a function

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/videojs-contrib-ads#281]
Hi, 

i am logging the player error and i found this error

player.ads is not a function 

i am using videojs 6.2.6

example of log errors

Type: WINDOWS Size: Desktop Browser: Chrome - 60.0 OSVersion: undefined Capability: Full player.ads is not a function
Type: WINDOWS Size: Desktop Browser: Firefox - 55.0 OSVersion: undefined Capability: Full player.ads is not a function 
Type: MAC Size: Desktop Browser: Safari - 10.1 OSVersion: undefined Capability: Full player.ads is not a function. (In &#39;player.ads(ads_plugin_settings)&#39;, &#39;player.ads&#39; is undefined)

**Comment by incompl** [comment]
Is the contrib-ads javascript included in your page? Is the request for it resolving correctly?

**Comment by misteroneill** [comment]
Also, which version of contrib-ads?

**Comment by ahmadawada11** [comment]
yes it is included and this is the link  [http://www.vod-platform.net/players/videojs6.2/videojs-contrib-ads/videojs.ads.min.js](http://www.vod-platform.net/players/videojs6.2/videojs-contrib-ads/videojs.ads.min.js)
videojs-contrib-ads @version 5.0.3

i am using the videojs.ima plugin to play the ads
[http://www.vod-platform.net/players/videojs6.2/videojs-ima/videojs.ima.js](http://www.vod-platform.net/players/videojs6.2/videojs-ima/videojs.ima.js)

**Comment by misteroneill** [comment]
May be related to #275

**Comment by misteroneill** [comment]
How are you including Video.js and videojs-contrib-ads? Script tags? A bundler of some sort (e.g. Browserify, WebPack, Rollup)?

**Comment by ahmadawada11** [comment]
i downloaded the files using NPM and included them in my project. 
please note this error randomly appear and i think the problem in videojs.ima plugin in line 1388  player.ads(ads_plugin_settings);

**Comment by ahmadawada11** [comment]
i think when the client has adblocker this error will appear.

**Comment by incompl** [comment]
Yeah that would definitely do it. Assuming this is resolved.
