### ISSUE TITLE
ads doesn't work on mobile

### ISSUE THREAD

**Issue by ahmadawada11** [videojs/videojs-contrib-ads#282]
Hi,

i trying to play ads on mobile using ima plugin they have the following example
[https://googleads.github.io/videojs-ima/examples/iPhone/](https://googleads.github.io/videojs-ima/examples/iPhone/ )
and this example
[https://googleads.github.io/videojs-ima/examples/advanced/](https://googleads.github.io/videojs-ima/examples/advanced/)

which working fine using video.js 5.3 but doesn't work with videojs 6.2.5 the ads load and hang
any help will be appreciated
thanks.

**Comment by ahmadawada11** [comment]
Hi,
according to google IMA documentation [https://developers.google.com/interactive-media-ads/docs/sdks/html5/mobile_video](https://developers.google.com/interactive-media-ads/docs/sdks/html5/mobile_video)  
**Both the content <video> element and AdDisplayContainer should be initialized within a user action. To initialize the content element, a call to the load() method is sufficient. To initialize the AdDisplayContainer, call the initialize()method in a user action**

so i removed the src from the video elemet and i assign it when the user click the player the ads start working, but if i wait for 5 seconds and then click the player the contrib-ads will throw exception "'videojs-contrib-ads has not seen a loadstart event 5 seconds..."

**Comment by theighost** [comment]
Hello,

I have the impression that the plugin doesn't work at all on mobile devices, I've been having this issue for a long time, even in the previews it doesn't work, tapping the play button does nothing and no errors are thrown in the errors field.

**Comment by incompl** [comment]
If you are getting the error "videojs-contrib-ads has not seen a loadstart event 5 seconds" I recommend taking a look at https://github.com/videojs/videojs-contrib-ads/#important-note-about-initialization on guidance to fix.

**Comment by incompl** [comment]
@ahmadawada11 Have you had a chance to look at the documentation in my last comment and try that out?

**Comment by incompl** [comment]
I'm going to close this since I haven't seen a response, please reopen if it's still an issue and you want further assistance.
