### ISSUE TITLE
player trigger nopostroll not working

### ISSUE THREAD

**Issue by SabaTD** [videojs/videojs-contrib-ads#285]
Hi, i have an issue,  i don't want postroll on my video. 
I removed "adPostTagUrl" from plugins array and added code.
`player.on("vast.contentStart", function () {
     player.trigger('nopostroll');
});`

I got javascript error :  [ VAST Error: on VASTClient.getVASTResponse, missing ad tag URL i {message: "VAST Error: on VASTClient.getVASTResponse, missing ad tag URL"} undefined

Any ideas what is wrong ?

**Comment by incompl** [comment]
What ad plugin are you using? One you built yourself with contrib-ads, or another one like videojs-ima?
