### ISSUE TITLE
integarate ads.js with dash.js and video-contrb-dash.js plugin

### ISSUE THREAD

**Issue by arunvjy** [videojs/videojs-contrib-ads#289]
[myadcode.txt](https://github.com/videojs/videojs-contrib-ads/files/1386832/myadcode.txt)
This plugin works fine when it separately loaded with Ads.( Not including dash.js and video-contrib.js)
When i integrate dash.js and video-contrib-dash.js to play the DRM protected content. The player.ads() function throws an error.

Uncaught TypeError: player.ads is not a function
    at new ImaPlugin (videojs.ima.js:1384)
    at Player.init (videojs.ima.js:57)

and another error was,

Uncaught TypeError: Cannot read property 'Events' of undefined
    at videojs.ads.js:11
    at videojs.ads.js:719 

These twp are the errors wat i got?

**Comment by incompl** [comment]
It looks like you are using Google's IMA plugin, I suggest opening a ticket
there: https://github.com/googleads/videojs-ima
