### ISSUE TITLE
Need your help | need pre roll ad to play with embedded videos...

### ISSUE THREAD

**Issue by tdcpepsi** [videojs/videojs-contrib-ads#297]
I have the youphptube video script and it use the videojs video player....

**My site:** vtubemobi.com

The pre roll ads will play uploaded videos but it won't play with the embedded videos, such as Youtube.
Is there a code to make the pre roll ads play with the embedded videos?

The youphptube people say that it can be done but they are not updating their project and have moved on to a new project.

I ask you because you are a coder and I can pay you if this can be done.

If this can be done in my site I will pay you. 
**Please reply if this can be done....**

**Comment by incompl** [comment]
@tdcpepsi This library is for creating videojs ad plugins from scratch, if you want a premade fully-baked ad plugin one you can check out is https://github.com/googleads/videojs-ima
