### ISSUE TITLE
Time of video isn't correctly restored after playing an ad

### ISSUE THREAD

**Issue by d3x7r0** [videojs/videojs-contrib-ads#303]
## Description
After playing an ad the time of the original video isn't always correctly restored. This only appears to happen in Mobile Safari on iOS 11 and the most recent version of Firefox. From my experiments it looks like setting currentTime before play is called doesn't work.

Reduced test case: http://jsbin.com/naqigu/edit?html,output

## Versions
* videojs-contrib-hls 5.1.3
* video.js 6.2.8

### Browsers
what browsers are affected? please include browser and version for each
* Mobile Safari - iOS 11 
* Mozilla Firefox 57 - Mac OS-X Sierra

**Comment by alex-barstow** [comment]
This will likely be solved as of the next release: https://github.com/videojs/videojs-contrib-ads/pull/290

**Comment by d3x7r0** [comment]
Cool! That's nice to hear. I missed the PR when searching through the open issues :)

Any idea when the release is coming out?

**Comment by incompl** [comment]
I'll do one right now so you can try it out

**Comment by incompl** [comment]
Published in 5.1.4, can you confirm if it's fixed?

**Comment by d3x7r0** [comment]
My first couple of tests in both Firefox and iOS Safari seem positive. The content resumed at the correct time.

**Comment by incompl** [comment]
Awesome, please reopen if seen again and we'll help figure it out.
