### ISSUE TITLE
HLS+ Preroll = TypeError: Cannot read property 'suppressedRemoteTracks' of undefined

### ISSUE THREAD

**Issue by Cogitoergo** [videojs/videojs-contrib-ads#304]
Greetings.

I'm trying to implement videojs player together with videojs-contrib-ads and videojs-contrib-hsl, but I fail.

I'm using NUXT.JS, with SSR Video.js mode.

I've read numerous issues out here, stating that this issue is now fixed, but it's really not. I've tried all the newest versions, tried all the forks from other folks, tried building it myself - I still get the same error.

Right after I press PLAY, I get a message saying
`video.cjs.js:17488 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22`

Then preroll plays, after it ends, I get another error: 
`console.js:32 VIDEOJS: ERROR: TypeError: Cannot read property 'suppressedRemoteTracks' of undefined`

As far as I understood from numerous topics here, It's because HLS videos have infinite duration, thus taking the snapshot fails.

This only happens when I'm trying to set the source in my sources array in video VUE.js component. If I set the source inside <source> tag, it plays just fine. So its seems it only appears on HLS sources set programaticly?

EDIT: Removing IF's from plugin.js in the following lines

`if (!player.ads.shouldPlayContentBehindAd(player)) {
      this.snapshot = snapshot.getPlayerSnapshot(player);
    }}
`

And

`  // Mute the player behind the ad
        if (player.ads.shouldPlayContentBehindAd(player)) {
          this.preAdVolume_ = player.volume();
          player.volume(0);
        `

Seems to solve the issue. Theres some idle time before playing content after ad, but at least it plays.

I guess I'm doing something wrong when implementing ads for live HLS, cause after the ad ended I'm trying to play the content from snapshot, but the snapshot is not there because of the two IF's above.

What would be the correct way to do this?

I have preroll-midroll-postroll for normal videos, and only a preroll for live HLS, I'm using the same method for them both.

How do I fix this? Do You need any more info from me? I've integrated the ads like in the example-integration.js file.

Thanks!

**Comment by incompl** [comment]
It's very interesting that it works unless you set the source in the sources array in the VUE.js component. Does the duration end up being Infinity in that case, but not if you set the source in the tag?

**Comment by Cogitoergo** [comment]
It seems, that it wouldn't capture the snapshot at all when the source is set in Vue data object. I removed both of the lines I've mentioned in OP and now it works, but theres 0.5-1s delay before playing the content after the ad has ended. I'll test further and report, perhaps make a pull request.

**Comment by incompl** [comment]
The purpose of those lines is for oncue ads during live streams, so we can't just remove them. In that case, there is no snapshot because the live stream continues to play muted behind ads. We need a way to figure out how to differentiate what's happening with your bug from the live stream behavior. That's why I wanted to know if the duration was infinity in the case you're seeing: if that was it, we'd need to find a way to accurately detect if it's really a live stream or not.

**Comment by incompl** [comment]
@Cogitoergo Have you learned anything new about your issue?

**Comment by incompl** [comment]
Closing because this issue is stale, but please feel free to reopen / create a new issue if you want additional assistance.
