### ISSUE TITLE
ad not playing in firefox

### ISSUE THREAD

**Issue by SolmazKh** [videojs/videojs-contrib-ads#307]
Hello.
I have recently upgraded my videojs library along with its plugins including contrib-ads.
The ad plays smoothly in chrome but in firefox it gives this error:

_VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect_

and it skips to the main video without showing the preroll ad.

How come this was not an error before?!
What should I do to fix this?

**Update 1:**
It randomly works fine.  However it gives this error: _InternalError: too much recursion_

**Comment by incompl** [comment]
This was added in 5.x to avoid a class of errors that was impacting a lot of our ad plugin users.

Here is information on what you need to do to address this issue: https://github.com/videojs/videojs-contrib-ads#important-note-about-initialization

If you post your plugin initialization code, I can help identify what needs to change.

**Comment by SolmazKh** [comment]
Thanks for the response. I had seen the link you gave but i still can't realize what exactly should I add to the code.
Unfortunately I don't have permission to share the code and even If I did I don't think you could understand. It's seprated in multiple files  and is a little complicated.
I am using the preroll plugin for videojs  [https://github.com/dirkjanm/videojs-preroll](url).
Shouldn't it be handled in the preroll plugin?!

**Comment by incompl** [comment]
I looked at videojs-preroll and I wasn't sure what version of videojs-contrib-ads that project was built for. I opened an issue there to clarify. They say it requires videojs-contrib-ads 3.x or newer, so you may want to try it with 3.x, 4.x, and 5.x and see if one of those versions works better with that project.

It's still possible this is fixable just in your integration though. [I opened an issue in videojs-preroll that has more information](https://github.com/dirkjanm/videojs-preroll/issues/29)

**Comment by SolmazKh** [comment]
I tried using your recommendation in [https://github.com/dirkjanm/videojs-preroll/issues/29](url).
It works fine. I will leave it at that until they fix this issue.
Thanks for your help

**Comment by incompl** [comment]
Happy to help!
