### ISSUE TITLE
Change Preroll, Midroll, Postroll on Demo Video

### ISSUE THREAD

**Issue by Sudhakar-Sukumar** [videojs/videojs-contrib-ads#322]
Hi
How can we change the preroll,midroll,postroll ads in the demo video player. Kindly guide us to change the ads.

**Comment by incompl** [comment]
What demo player are you referring to? videojs-contrib-ads is a library for creating ad integrations, which ad integration are you using?

**Comment by Sudhakar-Sukumar** [comment]
Sir

We are referring the below link
https://googleads.github.io/videojs-ima/examples/autoplay/

Kindly guide us to change the ads.

**Comment by Sudhakar-Sukumar** [comment]
Is there any chance to change the ads video in the below link

https://googleads.github.io/videojs-ima/examples/autoplay/

Kindly guide us to change the ads.

**Comment by incompl** [comment]
This example page is maintained by Google, you'll need to reach out to them. Maybe you could try opening an issue on https://github.com/googleads/videojs-ima
