### ISSUE TITLE
async pause throw silent exception

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#323]
I have question about using async setTimeout on many places in this library. I ask because videojs-ima via contrib-ads's function `cancelContentPlay` throws two silent exceptions (when user click to play and sources are not loaded yet):

> The play() request was interrupted by a call to pause()

videojs's play() returns Promise so it offers way to handle these tasks more gracefully. I am not using iOS so you probably know more about your current solution.

**Comment by incompl** [comment]
We are aware that this log message is a side-effect of how cancelContentPlay currently works. We are currently working on a new solution using [video.js middleware](https://blog.videojs.com/feature-spotlight-middleware/) to improve it.

**Comment by mysuf** [comment]
Sounds good. Thank you and many thanks to amazing community behind videojs. Its already few years since v1 and still alive and still evolving!
