### ISSUE TITLE
Contrib ads V6 not available

### ISSUE THREAD

**Issue by sdahdaah** [videojs/videojs-contrib-ads#331]
Hello,

contrib ads V6 CDN links not available and npm build version 5.1.6

regards,

**Comment by gkatsev** [comment]
It's available on npm and both [cdnjs](https://cdnjs.com/libraries/videojs-contrib-ads) (which we link to from the README) and [unpkg](https://unpkg.com/videojs-contrib-ads@6.0.0/) both have 6.0.
Hope that helps.
