### ISSUE TITLE
Ads problem

### ISSUE THREAD

**Issue by sdahdaah** [videojs/videojs-contrib-ads#333]
After updating to the latest version on IMA and Contrib-Ads only pre-roll is fired, mid-roll and post-roll are note being fired.

http://rs.vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw 

add to the above sometimes pre-roll is hanging after playing 1 second it shows the below error and hangs.

InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
videojs-contrib-hls.min.js:7

get
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:7:18485
value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:7:22963
value/<
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:11728
<anonymous> self-hosted:948:17 value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:12573
value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:12402
value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:11697
value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:8817
value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:7507
value
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:3:7301
value self-hosted:952:17 r
http://rs.vod-platform.net/players/videojs6.2/videojs-contrib-hls/videojs-contrib-hls.min.js:1:30294

Regards,

**Comment by incompl** [comment]
Are you using [videojs-ima](https://github.com/googleads/videojs-ima)? videojs-contrib-ads 6 just came out, and it is unlikely that they support it yet. Their package.json points to videojs-contrib-ads I would try again with videojs-contrib-ads `^5.1.6`. You can pick your desired version [using the CDN](https://cdnjs.com/libraries/videojs-contrib-ads) if that's your preference.

**Comment by sdahdaah** [comment]
I tried this version i got the same issue. If you remove rs and use
directly vod-platform.net those old versions are working correctly.

**Comment by incompl** [comment]
Can you update your example page to not use contrib-ads 6 so I can take a look at what happens in an environment that is known to work? Thanks!

**Comment by sdahdaah** [comment]
here is an example that uses contribads 5.0.3 the pre post and mid fires

http://vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1

below using 6.0 contrib ads with ima 1.1 pre sometimes fires mid and pre
never do

http://vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1

**Comment by incompl** [comment]
It sounds like videojs-ima does work with contrib-ads 5.x but not with 6.x, which is expected. I suggest using 5.x until videojs-ima is updated to support contrib-ads 6. I opened this issue to help hopefully clarify the dependency: https://github.com/googleads/videojs-ima/issues/533

**Comment by sdahdaah** [comment]
Do you suggest i keep 5.0.3 with latest IMA 1.1? Or i keep the versions i
have right now?

**Comment by sdahdaah** [comment]
By the way 5.1.6 had the same issue with latest IMA it is not only with 6 i
can create an example.

**Comment by incompl** [comment]
I suggest you keep using 5.0.3 if that works for you and report the issue with 5.1.6 to videojs-ima since that is the version they recommend using.

**Comment by sdahdaah** [comment]
let me give you a quick update, using contrib-ads V6 with IMA copyright
2014 had 0 issue and all worked well.

**Comment by sdahdaah** [comment]
Contrib-ads V6 and IMA v 0.8 is working with no issue.

**Comment by incompl** [comment]
After investigating, I don't believe I'm able to help you debug your issues with [videojs-ima](https://bithub.brightcove.com/videocloud/videojs-ima3/). I suggest opening issues in that project's github.
