### ISSUE TITLE
iOS iPhone - error 1009

### ISSUE THREAD

**Issue by sdahdaah** [videojs/videojs-contrib-ads#334]
Hello,

using the latest contrib-ads even with earlier versions whenever you try on iOS iPhone or using safari 11 with user-agent iOS iPhone the following link; http://vod-platform.net/Embed/uwPUXEHxeBRpHcpRmaronw?responsive=1 ads fire 1009 response.

any method to solve it.

**Comment by incompl** [comment]
After investigating, I don't believe I'm able to help you debug your issues with [videojs-ima](https://bithub.brightcove.com/videocloud/videojs-ima3/). I suggest opening issues in that project's github.
