### ISSUE TITLE
Log warning becomes less useful if code minified

### ISSUE THREAD

**Issue by incompl** [videojs/videojs-contrib-ads#338]
See: https://github.com/googleads/videojs-ima/issues/539#issuecomment-369944588

The log message is `video.bundle.js:5 VIDEOJS: WARN: Unexpected endLinearAdMode invocation (State via r)`. It says `r` instead of the state name because the code is minified.

We should update this message to not get messed up by minification.

**Comment by mysuf** [comment]
The non-minified msg is:

> video.bundle.js:9852 VIDEOJS: WARN: Unexpected endLinearAdMode invocation (State via AdsDone)

**Comment by mysuf** [comment]
It log out events in following order:
adsready
preroll playing(ok)
preroll ends(ok)
adend fires
video playing(ok)
video ends(ok)
delay few secs(nothing happens)
adtimeout fires
postroll playing(ok)
postroll ends(ok)
warn: unexpected endLinearAdMode invocation ..
allAdsCompleted(ima event) fires
adtimeout fires

**Comment by incompl** [comment]
@mysuf You'll want to post messages related to your specific videojs-ima issue back in https://github.com/googleads/videojs-ima/issues/539 so the maintainers of that project can help.

**Comment by incompl** [comment]
https://github.com/videojs/videojs-contrib-ads/pull/339

**Comment by incompl** [comment]
Fixed in 6.0.1.
