### ISSUE TITLE
how to change content source correctly

### ISSUE THREAD

**Issue by Pong420** [videojs/videojs-contrib-ads#346]
Hi,

i am working on resolution change by changing video source, but seems conflict with this plugin, player is stalled around 5 second after source change 

![screen shot 2018-03-08 at 11 46 38 am](https://user-images.githubusercontent.com/19869384/37132014-6e0e1618-22c6-11e8-8e0d-d1ab753c5192.png)

**Comment by incompl** [comment]
The main thing I suggest is to not do source changes during ad mode. Is `player.ads.isInAdMode()` true when you are changing sources? If you want to change sources during an ad, I suggest you first end the ad.

**Comment by Pong420** [comment]
`player.ads.isInAdMode()` is false

![screen shot 2018-03-09 at 11 04 36 am](https://user-images.githubusercontent.com/19869384/37188379-bd244eca-2389-11e8-9282-7d53cbdddad9.png)

**Comment by incompl** [comment]
Hmm this all seems OK. The error you're seeing in the console is a normal result of how `cancelContentPlay` works (we're changing how that works in [this PR](https://github.com/videojs/videojs-contrib-ads/pull/337) which will make that error go away).

I'm curious to know more about the state of the player when it is stalled. Is it paused? What is displayed visually?

If you could share an example that demonstrates the issue that would help a lot too.

**Comment by Pong420** [comment]
Sorry, i am not state clearly. 

**Action**
Change another video source and receive a `loadedmetadata` event

**Expectation**
The player continue to play

**Result** 
The player continue to play after 5 second

So my problem is how to remove the 5 second.
If set `timeout` to 0  work fine, but i worry that this may cause other problems

Here is the example, after video ad ended, click on the button to change video 
[https://ads-issue-346.herokuapp.com/
](https://ads-issue-346.herokuapp.com/
)

**Comment by incompl** [comment]
Ah I see, this is because the plugin does preroll checks again after you change sources. You can either play a preroll the same way you do for the initial source, or you can trigger a `nopreroll` event on the player like this: `player.trigger('nopreroll');`

**Comment by Pong420** [comment]
thanks so much~
