### ISSUE TITLE
create a video-js-contrib-ads npm module

### ISSUE THREAD

**Issue by jackson-sandland** [videojs/videojs-contrib-ads#349]
Welcome to videojs-contrib-ads and thank you for contributing to the project! Below is a template for filing issues that will help us diagnose problems and recommend solutions.

### Description

Installation is unclear, and unnecessarily convoluted. 

### Steps to Reproduce

Install by including a reference to said module in webpack via instructions in comments made between two developers in a pull request. 

#### Expected Results

install should be as simple as 
`npm install videojs-contrib-ads`

#### Actual Results

mentioned above

**Comment by gkatsev** [comment]
Hi, we do have it available for usage via npm. Seems like we're just missing that part of the docs in the README.

**Comment by incompl** [comment]
README updated, thanks for pointing out that this was missing!
