### ISSUE TITLE
Player triggers ended twice

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#358]
Using contrib-ads v6, player triggers ended event with contentended and then second time when postroll ends. It could break components that depends on ended event. Is this behaviour expected? I would expect that contrib-ads will throttle default ended event to end of postroll. Thanks.

**Comment by incompl** [comment]
Which version of contrib-ads are you using? There was an issue with double ended in 6.0.0 that was fixed in 6.0.1.

**Comment by mysuf** [comment]
Thats my case (using 6.0.0). I will check it with 6.0.1 and close this if it resolves that. Thank you.

**Comment by mysuf** [comment]
With 6.0.1 it seems even worse, because second ended event triggers earlier (together with adtimeout). I am using videojs-ima so it could be also related to videojs-ima issue.

**Comment by incompl** [comment]
Do you have an example I could look at to help diagnose the issue? It would also be useful to see if you can reproduce it in the [contrib-ads example integration](https://github.com/videojs/videojs-contrib-ads/tree/master/examples/basic-ad-plugin), because if you can, that shows it is a contrib-ads issue.

**Comment by mysuf** [comment]
This is part of event log from player instance when content video ends:

```
15.305s: timeupdate // playing content video
15.307s: timeupdate // playing content video
15.772s: timeupdate // playing content video
15.859s: timeupdate // playing content video
15.862s: pause // ima onAdBreakStart handles pause when contentended event 
15.867s: contentended
15.867s: ended
20.870s: ended
20.870s: adtimeout
```
Here is a sample page: https://games.tiscali.cz/player/vjs-testpage.html

Insert this into console before play:
```
var player = videojs.getAllPlayers()[0]
var defaultTrigger = player.trigger;
player.trigger = function(e, t) {
	console.log(e.type||e);
	return defaultTrigger.call(player, e, t);
}
```

**Comment by incompl** [comment]
I could not reproduce the issue with 6.0.1 in the sample page, which would be needed for me to expect ended to work correctly, did you try it that way?

**Comment by mysuf** [comment]
I will. I have many components including ima plugin that change source so ofc issue can be also there. I tried to find "trigger('ended" in whole project folder without any result. So I am thinking what can cause such behavior.. :/

**Comment by mysuf** [comment]
Yea. I understand. The only reason why I reported it here is because it happens at exactly same time as contrib-ads contentended ans adtimeout events.

**Comment by incompl** [comment]
OK cool, just wanted to provide the info in case it was helpful.

**Comment by mysuf** [comment]
This does not explain ended when contentended, but maybe explains second one. In sample above, there is missing adstart followed by adend when postroll plays. Is that why adtimeout triggers ended? If true, I will report it to videojs-ima.

**Comment by incompl** [comment]
The missing adstart / adend observation led me to understanding the issue. Adstart happens when the integration (in this case, videojs-ima) calls startLinearAdMode. This is when the ad beak begins. I noticed this in the debugger in your example page:

![screen shot 2018-03-28 at 3 41 08 pm](https://user-images.githubusercontent.com/211047/38052347-e9b6483e-329e-11e8-9f71-b4863e45a305.png)

It seems videojs-ima does not call startLinearAdMode for the postroll, so contrib-ads does not realize that an ad is playing. Notice the result of `player.ads.inAdBreak()` in the preroll vs. postroll. This would definitely explain strange behavior.

**Comment by mysuf** [comment]
Ok. I've got it. That makes sense. But does this bug explain ended together with contentended?

**Comment by incompl** [comment]
I'm not 100% sure, but the event redispatching relies on the player state matching what it expects, so it seems like a likely cause for this issue. [handleEnded in redispatch.js](https://github.com/videojs/videojs-contrib-ads/blob/master/src/redispatch.js#L69) checks both `isInAdMode` and `isContentResuming`, both of which could be wrong if an ad is playing without `startLinearAdMode` and `endLinearAdMode` being called.

**Comment by mysuf** [comment]
Ok. There is still chance that its my mistake, because I take care of ads.contentSrc everytime player.src() is changed (there is quality switcher and related videos). I still dont properly understand how IMA SDK handler when player's video element and changing source and when its own. On desktop its always new video elements created by SDK so I thought it wouldnt be a problem. I will check also this scenario and report it after proved. Thanks!

**Comment by mysuf** [comment]
Removed ads.contentSrc handling and still same so definetely ima issue.

**Comment by mysuf** [comment]
I tried your example and it looks correct and clear. So I am closing this issue as its probably all around ima implementation..
