### ISSUE TITLE
Statefull/OnlyThrottle switch feature

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#361]
Hi, I forked and refactored videojs-ima and it works, but have one unresolved question. Is possible to turn off statefull feature? There is a case where IMA SDK play ads outside content html5 element and without manipulation with content player. In this case, there is no reason to manipulate with src and drop out buffered content. So basically I want option to set contrib-ads only to throttle player's 'play' and 'ended' events. Everything else is handled by integration. Thanks.

P.S. second question is related `contentchanged`. It triggers only outside adbreak. I think it should trigger in adBreak too, because when it happens (for example via playlist outside player), integration cant handle it. The far best solution would be queue contentchange (and player.src) after endLinearAdMode when inAdBreak. I think that through middleware its possible.

**Comment by incompl** [comment]
contrib-ads has logic to only restore the source after an ad if the source was actually changed during the ad. This is the main line that handles it: https://github.com/videojs/videojs-contrib-ads/blob/master/src/snapshot.js#L195 Does that help?

Handling source changes during ad breaks is an interesting problem. In the past we have not had much success with it. Using middleware to queue the source change until after the ad break is an interesting idea. I'll give it some thought.

**Comment by mysuf** [comment]
I will check that later today. Thanks for info.

**Comment by mysuf** [comment]
It works exactly like you said. I thought that contrib-ads's snapshot cut source at startLinearAdMode and paste at endLinearAdMode. Dunno where found out that... Thanks!
