### ISSUE TITLE
contrib-ads handle player without adsready

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#362]
**What happens:** even without adsready, it calls adtimeouts and switch states

**What should happen:** without adsready, contrib-ads should be in idle state

**Affected versions:** 6.0.0, 6.0.1

**Options:**
```
{
  debug: true,
  timeout: 5000,
  prerollTimeout:5000
}
```

**Comment by incompl** [comment]
This is the intended behavior. The timeout begins on the "play" event because that is when playback is blocked by the ad plugin. After that point, content will resume after the timeout period, regardless of what it's waiting for.

**Comment by mysuf** [comment]
Ok. Got it. So integration should trigger both `nopreroll` and `nopostroll` if no ads are served but contrib ads is present.

**Comment by incompl** [comment]
Yup that's correct
