### ISSUE TITLE
no ad cause loading spinner on adsDone

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#368]
Hi,

when there is no linear ad at all and adsDone triggers, it adds vjs-ad-loading to player for rest of the player's life. This could be sensitive for non-linear ads. Console:

> VIDEOJS: ADS: Play middleware has been registered with videojs
> VIDEOJS: ADS: Using playMiddleware to block content playback
> VIDEOJS: ADS: Play call to Tech was terminated.
> VIDEOJS: ADS: Received play event (BeforePreroll)
> VIDEOJS: ADS: BeforePreroll -> Preroll
> VIDEOJS: ADS: Received nopreroll event
> VIDEOJS: ADS: Skipping prerolls due to nopreroll event (Preroll)
> VIDEOJS: ADS: Preroll -> ContentPlayback
> VIDEOJS: ADS: Received contentended event
> VIDEOJS: ADS: ContentPlayback -> Postroll
> VIDEOJS: ADS: Received nopostroll event
> VIDEOJS: ADS: Postroll -> AdsDone

**Comment by mysuf** [comment]
The most clear would be `setTimeout(preroll/postroll value)` method with one `isAdLoading(true)` inside and `clearTimeout(id)` with one `isAdLoading(false)`. Atm manipulating with vjs-ad-loading is on eight places.

**Comment by incompl** [comment]
Planning to do some additional testing before releasing this.
