### ISSUE TITLE
loading spinner issues

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#375]
Hi,

using v6.2.0, I see both classes `vjs-ad-playing` and `vjs-ad-loading` on player which displays loading spinner during ad playback. Console:

> VIDEOJS: ADS: Using cancelContentPlay to block content playback
> VIDEOJS: ADS: Received adsready event (BeforePreroll)
> VIDEOJS: ADS: Playback was canceled by cancelContentPlay
> VIDEOJS: ADS: Received play event (BeforePreroll)
> VIDEOJS: ADS: BeforePreroll -> Preroll
> VIDEOJS: ADS: Triggered readyforpreroll event (Preroll)
> VIDEOJS: ADS: Starting ad break

**Comment by mysuf** [comment]
For anyone facing this issue, temporary simple fix:

```
.vjs-ad-playing.vjs-ad-loading .vjs-loading-spinner {
	display: none;
}
```

**Comment by incompl** [comment]
Are you triggering `ads-ad-started` when the ad starts? This removes the loading spinner. Last week I updated the example in the docs to include this: http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html

**Comment by mysuf** [comment]
No. What is the purpose of this event? It will be probably triggered  by integration at same time as startLinearAdMode is called. Why not to remove spinner inside startLineatAdMode? Thanks

**Comment by incompl** [comment]
The main purpose is so that the loading spinner stays up until the exact moment an ad starts, which may be after startLinearAdMode.

**Comment by mysuf** [comment]
I think that it should not happen. Ofc it depends on integration but spinner on preroll/postroll loading is covered by adtimeout and midrolls should call startLinearAdBreak when its loaded and prepared to play.

**Comment by incompl** [comment]
I think the case it was built for was how you can startLinearAdMode, then put the ad source on the content video element, but it will still take time for the new source to actually start playing, especially on a mobile device / slow connection. A lot of stuff in this project was designed for pretty specific considerations like that.

**Comment by mysuf** [comment]
Yea. It sounds reasonable. I handle all of this by tech's `waiting` so I will fire this event with startLinearAdMode and let integration to manage the rest. Thanks!
