### ISSUE TITLE
VIDEOJS: ERROR: videojs-contrib-ads has not seen a loadstart event 5 seconds after being initialized, but a source is present. This indicates that videojs-contrib-ads was initialized too late. It must be initialized immediately after video.js in the same tick. As a result, some ads will not play and some media events will be incorrect. For more information, see https://github.com/videojs/videojs-contrib-ads#important-note-about-initialization

### ISSUE THREAD

**Issue by return-to-oz** [videojs/videojs-contrib-ads#377]
The link is not working:  https://github.com/videojs/videojs-contrib-ads#important-note-about-initialization

Using Pre-Roll ads plugin works, but when you stop the video after the ad and refresh chrome ad spins, hangs..

**Comment by incompl** [comment]
The updated link is here: http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html It has instructions on what is needed to resolve this.

**Comment by incompl** [comment]
Opened a PR: https://github.com/videojs/videojs-contrib-ads/pull/378

**Comment by incompl** [comment]
Fixed in 6.3.0
