### ISSUE TITLE
adpause event fires at wrong time

### ISSUE THREAD

**Issue by KevinBrogan** [videojs/videojs-contrib-ads#384]
The adpause event fires when the content is paused to start the ad, however, since the admode is active at that time, the event is prefixed with ad.

The ad itself is not being paused. The content prefix should be applied instead of the ad prefix.

**Comment by KevinBrogan** [comment]
any kind of user behavior tracking would require this.

**Comment by incompl** [comment]
The pause is not a user behavior, so at first blush, it appears the current behavior is correct. I believe a more detailed scenario may help clarify.
