### ISSUE TITLE
loading spinner on vjs-error

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#387]
Hi,

again issue related to loading spinner.) Class `vjs-ad-loading` remains on player when VIDEOJS error occurs (`vjs-error` is present).

Thanks

**Comment by incompl** [comment]
I could not reproduce this, what steps can we use to reproduce?

**Comment by mysuf** [comment]
Hmm..the only setting is `autoplay: true`.

**Comment by incompl** [comment]
When does the error occur?

**Comment by mysuf** [comment]
I cant reproduce it too. I saw there `vjs-ad-loading`, but now it seems broken by my own class `vjs-loading` as `vjs-waiting` is not added in all "waiting" cases and did not removed this custom class on error. Next time I will provide sample rather than false alarm. Sorry.
