### ISSUE TITLE
If the main content is an autoplaying HLS, loadedmetadata will fire for the preroll video

### ISSUE THREAD

**Issue by DoomTay** [videojs/videojs-contrib-ads#397]
### Description

If the main content is an HLS with autoplay, loadedmetadata will fire, but I will get back the attributes pertaining to the preroll ad instead of the main content.

http://jsfiddle.net/u2h0f86e/1/

So how am I supposed to be able to so something with the main content's duration, barring feeding my plugin a number?

#### Expected Results

Display the duration of the main content video (>500 seconds)

#### Actual Results

The duration of the ad will appear (~15 seconds)

### Versions

**videojs-contrib-ads version**: 6.3.0

**Video-js version**: 7.0.3

### Platforms

**Browsers**: Chrome v66.0.3359.181 and Firefox 60.0.2

**OS/Devices**: Windows 10

**Comment by incompl** [comment]
The reason this happens is really weird, so hold onto your hat. Loaded media events can happen really late, even _after the source has changed_. In 5.x we did a refactor of the event redispatching in this project and put a lot of thought into this problem. The solution can be seen in [`handleLoadEvent` in `redispatch.js` under the comment `Initial event`](https://github.com/videojs/videojs-contrib-ads/blob/master/src/redispatch.js#L108-L112). The code assumes that the initial load events are for the initial source, even if things have changed (so to speak). With careful testing we've confirmed this fulfills our contract that load events are not suppressed or duplicated. The fact that they happen when they do is a characteristic of browser behavior.

**Comment by mysuf** [comment]
I think that this is not that case. You are adding event listener to state of player that is already managed by contrib-ads (I guess that this state is garbage collected after ad playback, maybe @incompl can explain it better). If you add loadedmetadata event listener before calling `player.ads()`, it will persist through states..

**Comment by incompl** [comment]
contrib-ads emits an error if it's configured in a way that would miss load events. Adding event listeners before contrib-ads is initialized will result in other issues for sure, so that's worth checking too.

**Comment by mysuf** [comment]
> Adding event listeners before contrib-ads is initialized will result in other issues for sure
I dont understand. loadedmetadata is standardized media event and there are many other events added during player initialization (before player.ads()). What is different in this case?

**Comment by incompl** [comment]
Contrib-ads makes it so that ads don't trigger normal media events by way of [redispatch](http://videojs.github.io/videojs-contrib-ads/integrator/redispatch.html)

**Comment by mysuf** [comment]
Guuhhh..I thought that it redispatches only events related to ad playback. I didnt realized that event `contentloadedmetadata` even exists.. Thanks
