### ISSUE TITLE
videojs-contrib-ads not work

### ISSUE THREAD

**Issue by badrizahra** [videojs/videojs-contrib-ads#405]
i use videojs-contrib-ads exactly like this sample 
http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html

it has no console error  but it doesnt work and video doesnt play at all. 
can you help me?

**Comment by incompl** [comment]
If can you post a test page I'm happy to take a look.

**Comment by badrizahra** [comment]
thanks for your answer
i test it in a sample , simple project then i want to use in my main project
that's here : 
http://langclub.ir/assets/uploads/videojs-ads.zip

**Comment by incompl** [comment]
It appears your issue is not with contrib-ads, but rather with videojs initialization. I saw the issue with contrib-ads removed from the example. I recommend taking a look at the example here to debug: https://videojs.com/getting-started/

**Comment by badrizahra** [comment]
thanks a lot . that was right :)

**Comment by incompl** [comment]
Happy to help!
