### ISSUE TITLE
snapshot stores only one source

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#408]
Hi,

I found issue in contrib-ads's snapshot. We use multiple source tags inside HTML5 video element. The problem is that IMA SDK has reference to this tag and on mobile it changes src of native HTML5 video instead of using video iframe. I noticed that you detect this modification and restores previous source from snapshot. The issue is that you restore only one (current) source so we lost all other qualities after first snapshot. [This is problematic line that I am talking about](https://github.com/videojs/videojs-contrib-ads/blob/2ba443fce9036e1ba54448b187e7ad646ea1cd14/src/snapshot.js#L221).

You should snapshot all sources by `player.currentSources()`

Thanks

Btw. I store selected property in every source. If current source is selected by user through quality selector, I set `source.selected = true` for this source and then `player.src(currentSources)`. Because I have also  `sourceInterceptor` function like `videojs.use('*', sourceInterceptor)`, it handles rest of logic behind player's source selection..

**Comment by mysuf** [comment]
I think that [these changes](https://github.com/videojs/videojs-contrib-ads/compare/master...mysuf:snapshot-all-sources) should be enough to fix it. Can you look at it? Thanks

**Comment by incompl** [comment]
I took a look and talked to someone and we have feedback, can you make a formal PR so we can add comments?

**Comment by mysuf** [comment]
I found there several issues. It wouldnt be so easy. `currentSources()` returns newly created array when there is only one source. So it doesnt match to snapshoted currentSources even that object inside is the same (different reference to array). Best would be to get directly `player.cache_.sources` which is null when there is only single src, but it is internal property..

**Comment by incompl** [comment]
Planning to merge and release https://github.com/videojs/videojs-contrib-ads/pull/412 soon

**Comment by incompl** [comment]
Released in 6.4.3
