### ISSUE TITLE
show ads image before my video

### ISSUE THREAD

**Issue by badrizahra** [videojs/videojs-contrib-ads#409]
i test with an image sample before video it has this error : 
ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media

this error is logical but i want to know that can i have an image ads for some seconds before my video with vast??

**Comment by incompl** [comment]
Here is what the [VAST 3.0 spec](https://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf) states:

![screen shot 2018-07-19 at 10 15 02 am](https://user-images.githubusercontent.com/211047/42948040-a737be42-8b3c-11e8-9220-d0c90addcef1.png)

**Comment by incompl** [comment]
I see that thumbs up so I assume you're good and am closing this, feel free to reach out if you have any other questions!
