### ISSUE TITLE
ads cann't play when use flash tech

### ISSUE THREAD

**Issue by mraiguo** [videojs/videojs-contrib-ads#441]
### Description

ads cann't play when use flash tech

### Steps to Reproduce

here is my code： https://gist.github.com/mraiguo/c140e4f65190bfca081d245fee04013f

#### Expected Results

play the ad

#### Actual Results

there just show loading icon and after a few seconds，play the positive

### Versions

**videojs-contrib-ads version**: 6.6.1
**Video-js version**: 6.2.5

**Other plugins**: 
* videojs-flash@2；
* jquery@2.0.0
* videojs-swf@5.4.1

### Platforms

**Browsers**:  Chrome v69

**OS/Devices**: Windows 10

**Comment by incompl** [comment]
Flash support is no longer a goal of this project. If there is a reasonable PR that addresses this we can review it, but the maintainers will not be dedicating time to supporting Flash beyond that.
