### ISSUE TITLE
Custom snapshot's currentTime

### ISSUE THREAD

**Issue by mysuf** [videojs/videojs-contrib-ads#445]
My player currently saves time played to continue watching, but I would like to play also preroll before. Now it gets and sets currentTime() on loadedmetadata event which skips preroll (ima sdk evaluates that probably as "expired" when current time misses some time window), but occurs before currentTime is snapshoted so it properly seeks after preroll. 

Question: is there way or workaround how to play preroll and also set snapshot's currentTime > 0.0 (offset) ?  Thanks

Edit: Just found probably bug in debug mode. When debug is true, it skips preroll/postroll, plays content video, throws adtimeout and preserve loading spinner on top.. With debug off, it behaves as expected.

Edit2: Just found another bug. contrib-ads does not reset properly when adtimeout is pending and source is changed. After contentupdate, it plays preroll but does not switch back to content.. Log:

> VIDEOJS: ADS: Play middleware has been registered with videojs
> VIDEOJS: ADS: Received adsready event (BeforePreroll)
> VIDEOJS: ADS: Using playMiddleware to block content playback
> VIDEOJS: ADS: Play call to Tech was terminated.
> VIDEOJS: ADS: Received play event (BeforePreroll)
> VIDEOJS: ADS: BeforePreroll -> Preroll
> VIDEOJS: ADS: Triggered readyforpreroll event (Preroll)
> **VIDEOJS: ADS: contentupdate event**
> VIDEOJS: ADS: skipLinearAdMode (Preroll) **//called by integration to cleanup hanging events**
> VIDEOJS: ADS: Received adsready event (Preroll)
> VIDEOJS: ADS: Triggered readyforpreroll event (Preroll)
> VIDEOJS: WARN: Unexpected startLinearAdMode invocation (Preroll)
> VIDEOJS: ADS: adtimeout (Preroll)
> VIDEOJS: WARN: Unexpected skipLinearAdMode invocation

**Comment by incompl** [comment]
In your integration, would it work to set `player.ads.snapshot.currentTime = time` on `adstart`?

**Comment by mysuf** [comment]
The issue with adstart is that it triggers multiple times during content playback and also `.one` is not solution because there might be no preroll at all.

This is my current integration:
```
	player.on(['loadedmetadata', 'contentloadedmetadata'] , function() {
		player.one('playing', () => player.currentTime(lastTime||0));
	});
```
The downside of this solution is that it seeks after preroll so mostly its not buffered and loading spinner shows on top..

**Comment by incompl** [comment]
It's interesting that you get adstart events during content playback, the only place in videojs-contrib-ads where adstart is triggered is [when handling the start of an ad break](https://github.com/videojs/videojs-contrib-ads/blob/a533bbb5e85dc1501a1a0dec0e5dcce5876c8667/src/adBreak.js#L15). Do you know where those other adstarts are coming from?

**Comment by mysuf** [comment]
I mean adstart for preroll, each midroll and last for postroll.

**Comment by mysuf** [comment]
I'm not sure if there wasnt some event race condition on setting currentTime. I tried many ways but its already some time when I solved it. I'll give a try. Thanks

**Comment by incompl** [comment]
Got it working? 🤞

**Comment by mysuf** [comment]
@incompl I'll find out on Monday and let you know (and possibly reopen if not). thx
