### ISSUE TITLE
Preroll ad on Pixel 2

### ISSUE THREAD

**Issue by mihalikv** [videojs/videojs-contrib-ads#448]
### Description

Not working preroll ad on mobile.

### Steps to Reproduce

https://jsfiddle.net/cmeliak/13bL970f/3/
i just use example code from http://videojs.github.io/videojs-contrib-ads/integrator/getting-started.html

#### Expected Results

After click play button on video preroll should start playing.

#### Actual Results

Just mobile:

After click play button on video preroll is NOT played, just spinner is shown. But if i click small play/pause button in corner one more time, Ad is played.

### Versions

**videojs-contrib-ads version**: 6.6.0

**Video-js version**: 7.3.0

### Platforms

**Browsers**: eg. Chrome v70.0.3538.80 

**OS/Devices**: eg. Android 9.0.0 - also another androids

**Comment by incompl** [comment]
I just tried your example on Browserstack with Galaxy S9+ and Chrome and the preroll did play, is this still an issue?

**Comment by mihalikv** [comment]
Hi @incompl , sorry that i didn't try another android devices. It looks like every other devices works fine just Pixel 2 have some problems. I also try it on Nexus 5X with same Chrome version 70.0.3538.110 and it is good but Pixel 2 refuse to play video. So probably problem is just with pure android on Pixel 2.

**Comment by mihalikv** [comment]
@incompl Sorry i accidentally close issue.

**Comment by mihalikv** [comment]
Hi @incompl i try to test it one more time and... it works. Problem was that i always try that in "web for desktop" mode of chrome because of non responsive jsfiddle. [Video](https://drive.google.com/file/d/1hV5-2A7474YNrcOEuVfr4WQIFJSQh75G/view?usp=sharing) 
So sorry for raising issue this is just some edge case.

**Comment by incompl** [comment]
No problem, I appreciate folks taking the time to report issues even if they turn out to be nothing after investigation.
