### ISSUE TITLE
Can preroll ads be played without any video content?

### ISSUE THREAD

**Issue by Kasra-j** [videojs/videojs-contrib-ads#459]
This is more of a question than an issue! Sorry if this is not the right place to ask, couldn't find any other resource!

Is it possible to play preroll ads without any content being played on the player? so like something like the following snippet, which btw doesn't do anything and doesn't play the ad!

```
videojs.registerPlugin('vpaidPlugin', function() {
		const player = this

		player.ads();

                // fetch ad inventory here
               const src = src // from ad inventory fetch response

		player.trigger('adsready');

		player.on('readyforpreroll', () => {
			player.ads.startLinearAdMode();
			player.src(src);
		});

		player.one('adplaying', () => {
			player.trigger('ads-ad-started');
		});

		player.one('adended', () => {
			player.ads.endLinearAdMode();
		});
});

const player = videojs('vpaid_player', {
	controls: true,
	autoplay: true,
	preload: 'auto'
});

player.vpaidPlugin();

player.play();
```

**Comment by Kasra-j** [comment]
The answer was yes here! Closing this.

**Comment by incompl** [comment]
Nice, how did it work? If the solution makes sense maybe we can add it to the docs or as an example.

**Comment by TunayNovruz** [comment]
How i can do that ?  can you give code example ?

**Comment by ybbarng** [comment]
I tricked videojs-contrib-ads to play ads without video content.
```javascript
player.techCall_('play');
player.handleTechLoadStart_();
```
