### ISSUE TITLE
Unexpected startLinearAdMode invocation (Preroll)

### ISSUE THREAD

**Issue by arjitsachdeva** [videojs/videojs-contrib-ads#503]
Welcome to videojs-contrib-ads and thank you for contributing to the project! Below is a template for filing issues that will help us diagnose problems and recommend solutions.

### Description

A call to trigger the first ad break results in the Videojs warning: Unexpected startLinearAdMode invocation (Preroll), and it further leads to the second ad starting abruptly before the first one ends. 

### Steps to Reproduce

* First step

#### Expected Results

The content should have paused to make way for the ad to start playing. Then the second ad should have waited for the first one to trigger the end Linear Ad call. 

#### Actual Results

The first ad ends abruptly and the second ad starts playing. 

### Versions

All latest versions

**Other plugins**: please list other plugins that may affect videojs-contrib-ads behavior, especially ad plugins.

### Platforms

**Browsers**: Tested on latest Firefox and Chrome

**OS/Devices**: Mac OSX

**Comment by stomata** [comment]
when this happens, it will not show the class 'vjs-ad-playing'.
Videojs-ima will play the ad without the div => you can only hear the sound of the ad.
And when preroll is finished, the content won't automatically starts playback...

**Comment by stomata** [comment]
also the .play() would reject the promise.
