### ISSUE TITLE
Something wrong wrong with the repo

### ISSUE THREAD

**Issue by mayeaux** [videojs/videojs-contrib-ads#534]
When trying to submit a PR:
![Screen Shot 2021-10-12 at 9 34 14 PM](https://user-images.githubusercontent.com/7200471/137010425-093fbc8b-3cc2-4f5f-af31-0c98940de9e5.jpg

Also this:
![Screen Shot 2021-10-12 at 9 34 52 PM](https://user-images.githubusercontent.com/7200471/137010497-8e967935-2909-40fe-949b-aca5dde301e9.jpg)
)

What's going on? Can't star the project either

**Comment by gkatsev** [comment]
Please turn off your adblocker.
