### ISSUE TITLE
[YouTube/Google] ads are not loaded, VIDEOJS crash

### ISSUE THREAD

**Issue by santiagohdzb** [videojs/videojs-contrib-ads#55]
when you try to load this:
http://nhanhoasolutions.com/tam/html/ima/tam.html

```javascript
VIDEOJS: ads content-set -> ads-ready?
VIDEOJS: ads ads-ready? -> ad-timeout-playback
```

the main problem appears to be whenever this is loaded:
  http://imasdk.googleapis.com/js/sdkloader/ima3.js
it sends the video ads to the client, in this case the browser but they are not shown because VIDEOJS already crashed so you have to refresh the page or click the play triangle twice in order to see the ads

so in my conclusion google/youtube is taking so much time to send the video ads or at least more time than videojs.ads.js:**275** appears to wait for them so it triggers an error and crash. After this if you click the play triangle twice or refresh the page it already has the ads so it doesn't trigger the error.

maybe the solution could be changing the 5000 for 7000 or adding an extra Timeout layer... thanks

original reported by: @seekerquoc

**Comment by mente** [comment]
http://imasdk.googleapis.com/js/sdkloader/ima3.js stands for [Google IMA SDK](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/) and they have own [videojs plugin](https://github.com/googleads/videojs-ima) integrating ads. IMHO you should first try using it.

**Comment by dmlap** [comment]
Haven't heard back on this one in awhile, so I'm going to close it. If you're still running into issues, I would recommend giving @mente's advice a shot.
