### ISSUE TITLE
Latest version of videoJs (4.11.4)  fails with version 1.0.0 of videojs-contrib-ads

### ISSUE THREAD

**Issue by carpasse** [videojs/videojs-contrib-ads#66]
I have updated from version 0.5.0 of videojs-contrib-ads to 1.0.0 and I get an error on getPlayerSnapshot

on line 149 of videojs.ads.js
```
 tracks = player.remoteTextTracks(),
```

I have not been able to find this function 'remoteTextTracks' on the latest version of the player (4.11.4) or in any previous versions.
 
I imagine that if it had to exist, it should be defined in https://github.com/videojs/video.js/blob/master/src/js/tracks.js but I could not find it.

**Comment by gkatsev** [comment]
Yes, you're right. There's a PR out to fix it.
remote text tracks are coming to videojs very very soon.

**Comment by carpasse** [comment]
Do you know when will this PR be merged?
And more important when will there be a new version of the player containing the PR???

**Comment by gkatsev** [comment]
Hopefully both videojs and contrib-ads will get updated really soon :)

**Comment by gkatsev** [comment]
Sorry for the issues.

**Comment by dmlap** [comment]
We now test for the presence of remoteTextTracks in contrib-ads and the latest version of video.js includes that functionality by default.

**Comment by carpasse** [comment]
Thanks fro the fix @gkatsev
