### ISSUE TITLE
Update bower version from 0.2.0 to 1.0.0

### ISSUE THREAD

**Issue by carpasse** [videojs/videojs-contrib-ads#67]
Hi guys 
I just realized that bower version is 0.2.0 but the latest release is 1.0.0
It may be good to update the version number in bower.json

**Comment by dmlap** [comment]
Good thinking. Thanks for the report.

**Comment by adamgoose** [comment]
20 days, and no update? +11

**Comment by dmlap** [comment]
@adamgoose yeah, sorry. We've been distracted with enhancing support for playlists. If you're willing to try out a PR, we'd be happy to merge it.
