### ISSUE TITLE
fallback src types

### ISSUE THREAD

**Issue by billyrennekamp** [videojs/videojs-contrib-ads#68]
how do you decide which format to serve as the ad?  do i need to browser detect inside of player.ad() in order to help me choose which file to give to player.src()?

**Comment by dmlap** [comment]
As long as it's a format supported by video.js, you can load it directly if you know the video MIME type:

```js
player.src({
  src: "https://example.com/ad.mp4",
  type: "video/mp4"
});
```

**Comment by billyrennekamp** [comment]
i'd like to do something like this:
```
player.src({
    {src: "http://example.com/ad.mp4", type: "video/mp4"},
    {src: "http://example.com/ad.webm", type: "video/webm"}
});
```
so that the ad will have a fallback format to play on browsers that don't support mp4.
is that possible or do i need to decide manually which format is appropriate for the browser before feeding it to player.src()?

**Comment by billyrennekamp** [comment]
i see now that it also accepts an array of video objects.
that's perfect thank you very much!
