### ISSUE TITLE
function remoteTextTracks renamed

### ISSUE THREAD

**Issue by DLuPi** [videojs/videojs-contrib-ads#69]
Hi, as user [mcountis](https://github.com/mcountis) found out, the function ```remoteTextTracks()``` in videojs, has been renamed in ```textTracks()```.
Using [IMA](https://github.com/googleads/videojs-ima) plugin, this issue prevents the ui elements (countdown/progress bar) and controls of the AD to play properly. (In my case).

**Comment by gkatsev** [comment]
Sorry for the problems. `remoteTextTracks` is a new feature that will be shipping in videojs soon.
We'll get a new version of ads out that doesn't break for this, soonish.

**Comment by DLuPi** [comment]
Thank you! ;)

**Comment by gkatsev** [comment]
The feature just landed in videojs master.

**Comment by gkatsev** [comment]
`remoteTextTracks` is going to be in an upcoming (hopefully today) version of videojs.
Meanwhile, we hopefully have a fix for it in v1.0.1.

**Comment by DLuPi** [comment]
Thank you!
Il 17/feb/2015 18:12 "Gary Katsevman" <notifications@github.com> ha scritto:
