### ISSUE TITLE
Support HLS and dash

### ISSUE THREAD

**Issue by OrchidVC** [videojs/videojs-contrib-ads#71]
I add videojs-contrib-hls library to your example, when run example:
- Run success with mp4 type
- When run with source type dash or hls, the event "contentupdate" always show when load page finish with contents:
[1425893852266] contentupdate: 
  oldValue: http://222.255.37.148/film.m3u8
  newValue: blob:http%3A//localhost%3A3000/ffc45305-8c95-459f-967d-804bb082cf8f
player can't play anything when ads finish playing. I don't know why src of player changed to invalid link??
 
I have a question: videojs-contrib-ads support HLS and dash type???

**Comment by dmlap** [comment]
I've done work with a custom ad integration built on top of contrib-ads that uses videojs-contrib-hls without issues. What version ads/hls are you using? Do you have an example anywhere that reproduces the issue?

video.js doesn't support DASH without the use of additional plugins/techs. What are you using to get DASH support?

**Comment by OrchidVC** [comment]
I use videojs-tech-dashjs support DASH for videojs, details on attach file

Now, I change example by removing dash and use only hls with your ads
library, but something go wrong when click button play, videojs throw
invalid exception
 - hls library version 0.11.0
 - ads library version 0.5.0
 - videojs version 4.12.4
I also attach sample file and error image

Thanks and regards

**Comment by dmlap** [comment]
@OrchidVC it doesn't look like your attachments made it through. Can you retry?

**Comment by OrchidVC** [comment]
I run at localhost with index.html, that exception always occurs.
Server: nodejs
Can you tell me which version of library you using??

**Comment by dmlap** [comment]
I saw a number of errors trying your example. First, it seems like one of the media m3u8s is not available. That could be causing other issues. Do you see this problem with a fully working m3u8? If so, it might be better to refile this over in contrib-hls. There are a lot of errors being generated by this stream and that could very likely be breaking ads.

**Comment by dmlap** [comment]
I'm closing this one since we haven't heard back. Please reopen it if you've fixed up the other problems in your page and are still seeing the issue.
