### ISSUE TITLE
How to hide controls bar while playing video ads

### ISSUE THREAD

**Issue by shivamg705** [videojs/videojs-contrib-ads#74]
Can i hide controls bar while playing video ads.

**Comment by dmlap** [comment]
The class `vjs-ad-playing` is added to the player while ads are in progress. You can see an example of using that class to [customize styling during ad playback](https://github.com/videojs/videojs-contrib-ads/blob/master/src/videojs.ads.css#L6) in videojs.ads.css.

**Comment by shivamg705** [comment]
Thanks for your support
