### ISSUE TITLE
Add an `adscanceled` transition events from `ads-ready` and `preroll?` in the FSM

### ISSUE THREAD

**Issue by pcting** [videojs/videojs-contrib-ads#75]
### Proposal
The FSM should include an `adscanceled` event to leave the `ads-ready` and `preroll?` states.

### Reason
Lets assume there's a playlist plugin loaded. At any given time, a "play the next item" event could be triggered. From a UX perspective, the AD integration should immediately drop out of playing or loading the AD to fulfill the request. However, if you're in the `ads-ready` state, your only immediate option is to trigger an `adserror`. If you're in the `preroll?` state, you can trigger a `adtimeout` or `adserror`, but it feels like `adscanceled` is most appropriate.

**Comment by gkatsev** [comment]
We have such (or similar) event. Hopefully, it matches what you need:
>  adscanceled (EVENT) — Trigger this event after starting up the player or setting a new video to skip ads entirely. This event is optional; if you always plan on displaying ads, you don't need to worry about triggering it. (https://github.com/videojs/videojs-contrib-ads#developing-an-integration)

Going to close this, but if you feel like your proposal is different enough from our current event, please comment and we can reopen. Please continue discussion here, if needed.
