### ISSUE TITLE
Resume m3u8 playing after ad showing

### ISSUE THREAD

**Issue by waster** [videojs/videojs-contrib-ads#77]
After https://github.com/videojs/videojs-contrib-ads/commit/eb57aba42b287512ccd8570f0518805c7819e9d0 commit m3u8 stopped to resume playing after showing ad. I'm using [flashhls](https://github.com/mangui/video-js-swf) videojs plugin + [vast](https://github.com/theonion/videojs-vast-plugin) plugin(updated to work with current contrib-ads) and contrib-ads from current master git. Before that commit resuming worked well.

I guess the problem is that contentcanplay did not fire in case of m3u8 use. But contentloadedmetadata event fired well.

Will check with the currnet contrib-hls and post results too.

With regards, Andrey.

**Comment by waster** [comment]
I checked example in git and remove autoplay attribute. Now ad is playing after clicking to play but initial source don't start after ads. May be it's right to start initial source after ad show automatically?

**Comment by waster** [comment]
Ok. Tested with contrib hls and it works but spinning loader is shown permanently in case of m3u8 initial source. For mp4 loader hides after initial load of ad,

**Comment by dmlap** [comment]
What ad integration are you using on top of contrib-ads? Any chance you have a public example available?

**Comment by waster** [comment]
Sure. [Here](http://77.221.142.84:8081/live/videojs-contrib-ads/example/) is the example from master branch with update to use flashhls.

**Comment by gkatsev** [comment]
I know there were some changes we had to make to the videojs swf around pause state to go with this update. The flashhls swf project probably needs to pick them up.

**Comment by waster** [comment]
Hm, I created [test](http://77.221.142.84:8081/live/videojs-contrib-ads/example/index-contrib.html) with videojs-contrib-hls 0.11.2 and spinner do not work also with provided HLS stream. Content resuming works with some latency from time to time. I guess it depends on x264 GOP length (ffmpeg -g ) a video stream?

**Comment by dmlap** [comment]
@waster can you help us narrow down the situations where resuming isn't working? Your test link seemed to be working for me on win7/chrome.

**Comment by waster** [comment]
@dmlap Yes, now resuming works well with videojs-contrib-hls (spinner is still showing) but with flashls it does not (you can check test link again). I guess it's up to developer of this project to pick some changes as @gkatsev mentioned.

**Comment by dmlap** [comment]
Yeah, I think it is. If new evidence turns up that points to contrib-ads though, please re-open this issue.
