### ISSUE TITLE
When calling player.ads() autoplay does not work anymore and click to play requires two clicks

### ISSUE THREAD

**Issue by premesh** [videojs/videojs-contrib-ads#79]
http://192.237.149.165/video/demo/video.html

not sure if im doing something wrong but if i have the player.ads() call in my videojs callback function then it seems like it breaks the click to play functionality. If i set autoplay to true then it still requires a click... am i missing something?

**Comment by bclwhitaker** [comment]
The contrib-ads plugin is intended as a building block for a more complete ad integration.  Whenever new content is set in the player it will begin intercepting play requests to give ad integrations a chance to play a preroll.

See the https://github.com/videojs/videojs-contrib-ads#state-diagram

If you aren't going to play any ads you can simply call player.trigger('adscanceled') after you instantiate the plugin and it should no longer intercept play events.  You would need to trigger this event whenever you change the source of the player.

**Comment by premesh** [comment]
perfect thanks for the info
