### ISSUE TITLE
Bug: playback always resuming after postroll

### ISSUE THREAD

**Issue by philotas** [videojs/videojs-contrib-ads#85]
in the `resume` function inside the `restorePlayerSnapshot` there is a fix for iOS 8.1 (`ended` event not firing when seeking to the end)

This fix however causes the video to resume playback always even after returning from a postroll even if `snapshot.ended ==  true`

```javascript
      // finish restoring the playback state
      resume = function() {
        var
          ended = false,
          updateEnded = function() {
            ended = true;
          };
        player.currentTime(snapshot.currentTime);

        // Resume playback if this wasn't a postroll
        if (!snapshot.ended) {
          player.play();
        } else {
          // On iOS 8.1, the "ended" event will not fire if you seek
          // directly to the end of a video. To make that behavior
          // consistent with the standard, fire a synthetic event if
          // "ended" does not fire within 250ms. Note that the ended
          // event should occur whether the browser actually has data
          // available for that position
          // (https://html.spec.whatwg.org/multipage/embedded-content.html#seeking),
          // so it should not be necessary to wait for the seek to
          // indicate completion.
          window.setTimeout(function() {
            if (!ended) {
              player.play();
            }
            player.off('ended', updateEnded);
          }, 250);
          player.on('ended', updateEnded);
        }
      },
```

I don't understand why there is this iOS 8.1 Seeking fix inside the resume function for restoring the snapshot, but I guess a simple fix would be to on set the timeout if `snapshot.ended == false `?

**Comment by dmlap** [comment]
What platforms are you seeing the video resuming after postrolls on? By "resuming", do you mean replaying the original video?

**Comment by philotas** [comment]
Correct, I mean replaying the original video.

Just did some more testing on my OS X 10.9.5 Machine:

Problem occurs on:
Safari, Chrome, Opera

Does NOT occur on:
Firefox, FirefoxDeveloperEdition and Safari on iPad 2 (iOS 8.1.3)

**Comment by philotas** [comment]
no ideas?

**Comment by dmlap** [comment]
I haven't seen this behavior in any of my testing. Are you using any other plugins in conjunction with this project? Do you have a public example we could look at?

**Comment by dmlap** [comment]
Closing this since we haven't heard back in awhile. Please re-open if you're still running into this problem.

**Comment by jpfranco** [comment]
Hey guys, I'm also experiencing this issue. I currently don't have a lot information about it, but I'm able to reproduce it every time on Safari (desktop) as long as there are both a pre-roll and a post-roll configured. If you cancel the pre-roll the issue seems to go away. In Chrome this seems to happen randomly, so I'm not sure under what conditions it arises.

I think Google ran into the same problem with their IMA plugin. Take a look at this comment on their source code:
![screen shot 2015-05-27 at 11 25 03 am](https://cloud.githubusercontent.com/assets/1322503/7844267/fd508560-0463-11e5-9303-17c47db460d2.png)
:
