### ISSUE TITLE
Fail to running example videojs-contrib-ads.

### ISSUE THREAD

**Issue by kipotlea** [videojs/videojs-contrib-ads#86]
Fail to running example videojs-contrib-ads.
I'm download videojs-contrib-ads. I running it in my localhost. But it is not working. I have some error like this.

Uncaught ReferenceError: videojs is not defined
example-integration.js:127 Uncaught ReferenceError: videojs is not defined
localhost/:47 Uncaught ReferenceError: videojs is not defined

How to fix it?

**Comment by philotas** [comment]
The links to the video.js files are not working as the example as it is will actually will only work if you have installed the dev dependencies.
Instead of doing this you can directly reference a video.js and the css in the cloud instead of local:
change:
```html
  <!-- Load local video.js -->
  <link rel="stylesheet" href="../node_modules/video.js/dist/video-js/video-js.min.css">
  <script src="../node_modules/video.js/dist/video-js/video.dev.js"></script>
```
to:
```html
<!-- Load video.js from cdn -->
  <link rel="stylesheet" href="http://vjs.zencdn.net/4.12.5/video-js.css">
  <script src="http://vjs.zencdn.net/4.12.5/video.js"></script>
```

**Comment by kipotlea** [comment]
thank you @philotas  . it works

**Comment by dmlap** [comment]
@philotas seconded-- thanks for helping out!
