### ISSUE TITLE
HLS or Youtube causes midroll AD to not resume content playback

### ISSUE THREAD

**Issue by gotling** [videojs/videojs-contrib-ads#88]
I am trying to use the ads plugin to play midroll ads in mp4, HLS, and Youtube videos.

Playing mp4 files with ads is working fine but I have problems with HLS and Youtube:
- HLS videos don't get their content length reset and sometimes playback doesn't start again.
- Youtube videos loses Video JS skinning and doesn't start again.
# Demo

I have made examples of the problems here:
## Online

http://gotling.github.io/videojs/ads-hls-youtube.html
## Code

https://github.com/gotling/video-js-hls-youtube/
Specifically see [ads-hls-youtube.html](https://github.com/gotling/video-js-hls-youtube/blob/master/ads-hls-youtube.html)
# Versions

videojs-4.12
videojs-contrib-ads-2.1.0
videojs-contrib-hls-0.12.0
videojs-contrib-media-sources-0.3.1
videojs-youtube-1.2.10
# Browsers tested
## Mac OS 10.10.2

Chrome 42.0.2311.90
Firefox 37.0.1
Safari 8.0.4

**Comment by dmlap** [comment]
Would you mind putting your example page on github pages? It would speed up debugging a bit.

**Comment by gotling** [comment]
I have now put up an online demo on Github pages:
http://gotling.github.io/videojs/ads-hls-youtube.html

**Comment by gotling** [comment]
As a workaround I have added 2 players to the page. One showing a clip and which contrib-ads is initialized against. Another one which is responsible for displaying ads.

This works ok after some struggling with hiding the Flash object, but now I have to exit fullscreen mode to show ads and can not enter it again programatically.

**Comment by incompl** [comment]
A lot has changed in how snapshot works and we use midrolls + HLS all the time, so I'm going to assume this has been fixed in the past year and a half. Please reopen if I'm mistaken.
