### ISSUE TITLE
vjs-play-progress width: 39944.01%?

### ISSUE THREAD

**Issue by izemize** [videojs/videojs-contrib-ads#90]
Hi

I play live rtmp stream, and after ads play end, i have progress bar overflow.

``` html
<div class="vjs-play-progress" style="width: 41504.91%;"><span class="vjs-control-text"><span>Progress</span>: 0%</span></div>
```

I think ads plugin calculate position from 0:00:00 after ads ends, but live stream is started / continued from 1:10:55

**Comment by dmlap** [comment]
The midroll workflow in contrib-ads is really centered around VOD content today. We definitely need to do some thinking about how to organize it to be helpful for live advertisement. Do you have any suggestions on how you'd like contrib-ads to behave around midrolls in live streams?

**Comment by incompl** [comment]
A lot of work has been done to support live video since this issue was opened, so I'm assuming this issue has been addressed. Please reopen if I'm mistaken.
