### ISSUE TITLE
.vjs-has-started class not being added to the player when the ad plays

### ISSUE THREAD

**Issue by carpasse** [videojs/videojs-contrib-ads#93]
Hi guys

I have migrated from 1.1.0 to 2.1.0 and one of the biggest issues that I found was that the class 
'vjs-has-started' was not added to player when the ad was playing. 

This prevented the poster from disapearing when the ad was playing and the control bar from appearing and disappearing (when the user was active or inactive). 

In the end I had to ad the following styles to my css

```
.vjs-ad-playing .vjs-poster {
  display: none;
}

/* Show the control bar only once the video has started playing */
.vjs-ad-playing .vjs-control-bar {
  display: block;
  /* Visibility needed to make sure things hide in older browsers too. */

  visibility: visible;
  opacity: 1;
  /* transition */
  -webkit-transition: visibility 0.1s, opacity 0.1s;
  -moz-transition: visibility 0.1s, opacity 0.1s;
  -o-transition: visibility 0.1s, opacity 0.1s;
  transition: visibility 0.1s, opacity 0.1s;
}

/* Hide the control bar when the video is playing and the user is inactive  */
.vjs-ad-playing.vjs-user-inactive.vjs-playing .vjs-control-bar {
  display: block;
  visibility: hidden;
  opacity: 0;
  /* transition */
  -webkit-transition: visibility 1s, opacity 1s;
  -moz-transition: visibility 1s, opacity 1s;
  -o-transition: visibility 1s, opacity 1s;
  transition: visibility 1s, opacity 1s;
}
```

I think we should add the previous styles to the plugin (they are pretty much copy pasted from vjs default skin) or investigate why the class 'vjs-has-started' is not being added to the player.

**Comment by carpasse** [comment]
It took me a while but I finally found why the heck the 'vjs-has-started' class is not being added.
The problem is that we are redispatching the 'play' event when the state is 'ad-playback'

```javascript
redispatch = function(event) {
  if (player.ads.state === 'ad-playback') {
     triggerEvent('ad', event);
```
since the event propagation gets stopped when you call 'triggerEvent' the handler inside 'onLoadStart' never gets called.

```javascript
/**
 * Fired when the user agent begins looking for media data
 * @event loadstart
 */
vjs.Player.prototype.onLoadStart = function() {

  // reset the error state
  this.error(null);

  // If it's already playing we want to trigger a firstplay event now.
  // The firstplay event relies on both the play and loadstart events
  // which can happen in any order for a new source
  if (!this.paused()) {
    this.trigger('firstplay');
  } else {
    // reset the hasStarted state
    this.hasStarted(false);
    this.one('play', function(){
      this.hasStarted(true);
    });
  }
};
```
the call to ```this.hasStarted(true)``` ads the 'vjs-has-started' class
Once you know the problem the fix is always easy, we just need call the 'player.hasStarted(true)' on the redispatch function if the event is 'play'

```javascript

redispatch = function(event) {
   if (player.ads.state === 'ad-playback') {
      triggerEvent('ad', event);
      if(event.type === 'play'){
           player.hasStarted(true);
       }
...
```

I can do a PR if you agree with the fix. :)

**Comment by carpasse** [comment]
I missed one corner case on my previous solution. In the end I had to add the if at the beginning of the redispatch function and check the ads state:
```javascript
 redispatch = function(event) {
     if(event.type === 'play' && (player.ads.state === 'ads-playback'|| player.ads.state === 'content-resuming')){
         player.hasStarted(true);
     }
          
     if (player.ads.state === 'ad-playback') {
         ...
```

**Comment by dmlap** [comment]
@carpasse thanks for the investigation! We'll have to get this fixed quickly. Any chance your modifications are in good shape to turn into a PR?

**Comment by carpasse** [comment]
@dmlap I can do a PR with the change but it will now work with the mangled version of videojs https://github.com/videojs/video.js/issues/2279 for some reason player.hasStarted is not available.
Should I do a PR with the css fix or with the player.hasStarted call??

**Comment by imbcmdth** [comment]
This issue was fixed in video.js v4.12.0 and later.
