### ISSUE TITLE
Update proposal in the Migration guide

### ISSUE THREAD

**Issue by carpasse** [videojs/videojs-contrib-ads#94]
At the end of the migration guide, it says:

```
The extended support for postrolls added a new `postrollTimeout` option, similar to prerolls.
If you do not wish to play a postroll for a video, you can fire `adtimeout` to proceed to the next video immediately.
```

I thing there is an even easier way to disable postroll ads. You just have to add the 'postrollTimeout' option with 0 value and that will do the trick. 

I was going to do a PR but thought it may be worth it to discuss it first just in case.

**Comment by dmlap** [comment]
I've always thought using `adtimeout` to skip an ad opportunity was a little weird. I guess `postrollTimeout = 0` basically accomplishes the same thing, but it strikes me as a bit odd too. What about introducing a new event that is named more appropriately and using it?

**Comment by carpasse** [comment]
I rather have a configuration option to just disable postroll ads. If you are not going to support them then we should make them easy to disable. We should probably do the same regarding preroll ads.

**Comment by dmlap** [comment]
I think some ad libraries ([videojs-ima](https://github.com/googleads/videojs-ima) for example) don't allow you to skip prerolls or postrolls so adding a configuration option like to drop them unconditionally would cause them to malfunction. Any alternative sound appealing?

**Comment by incompl** [comment]
A `nopreroll` event has been added since this issue was opened, so I think we're good now.
