### ISSUE TITLE
How to configure this plugin without mid roll ads

### ISSUE THREAD

**Issue by shivamg705** [videojs/videojs-contrib-ads#98]
You have designed great plugin for playing video ads.

I need a plugin with videojs which can support only pre and post roll ads.
so can you tell me how to configure your plugin with only pre and post roll without mid roll.

Thanks in advance

**Comment by MartinDesigner** [comment]
Hey! I just read You are working on designing and including ads into your website content as html (and/or image also?) I know another perfect solution for You - how to easily design ads from predesigned templates and embed them into any html site - however mean interactive htmls/js/css based ads, not video. I got hope it will also improve Your work, as I'm sure of it :-) This is it (agile description of app which I'm telling about):
![imghome](https://cloud.githubusercontent.com/assets/13809960/9289329/0bef602c-436c-11e5-80fc-3ec07f82dd8d.jpg)
So, I propose you to try and explore this amazing free app for visual online designing and online publishing. Createer.com is an online software for easily designing online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates (browse here: https://beta2.createer.com/Templates?ghi) and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment. And finally this amazing stuff is here: https://beta2.createer.com/?ghi

**Comment by incompl** [comment]
This plugin supports pre and postroll ads without midrolls without any issues. You need to build your ad integration in a way that midrolls are not triggered.
